#!/usr/bin/env bash
# scripts/whatsapp/install.sh — installs the WAHA WhatsApp gateway for
# vps-manager. Idempotent (re-runs are safe).
#
# What it does:
#   1. Creates /var/lib/vpsm-whatsapp/{sessions,media,files} (mode 0700)
#   2. Lays down /opt/vpsm-whatsapp/{docker-compose.yml,.env}
#   3. Generates random WAHA_API_KEY + WAHA_HMAC_SECRET (preserved on re-run)
#   4. Mirrors the secrets into the vps-manager secrets vault so the Go
#      service picks them up on next restart
#   5. Installs the systemd unit /etc/systemd/system/vpsm-whatsapp.service
#   6. Enables (but does NOT auto-start — user clicks "Connect" in the UI)
#
# After this script: restart vps-manager so it reads the vault, then go to
# /whatsapp in the panel and click "Conectar".

set -euo pipefail

if [ "${EUID:-$(id -u)}" -ne 0 ]; then
  echo "this script must run as root" >&2
  exit 1
fi

REPO_DIR="${REPO_DIR:-/opt/panel}"
INSTALL_DIR="/opt/vpsm-whatsapp"
DATA_DIR="/var/lib/vpsm-whatsapp"
UNIT_DST="/etc/systemd/system/vpsm-whatsapp.service"
UNIT_TMPL_DST="/etc/systemd/system/vpsm-whatsapp@.service"
COMPOSE_SRC="${REPO_DIR}/scripts/whatsapp/docker-compose.yml"
UNIT_SRC="${REPO_DIR}/scripts/whatsapp/vpsm-whatsapp.service"
UNIT_TMPL_SRC="${REPO_DIR}/scripts/whatsapp/vpsm-whatsapp@.service"
VPSM_DATA="${VPSM_DATA:-/opt/panel/data}"
VAULT_HELPER="${REPO_DIR}/scripts/whatsapp/vault-put.sh"

bold() { printf "\033[1m%s\033[0m\n" "$*"; }
ok()   { printf "  ✓ %s\n" "$*"; }
warn() { printf "  ⚠ %s\n" "$*" >&2; }
fail() { printf "  ✗ %s\n" "$*" >&2; exit 1; }

bold "→ Checking prerequisites"
command -v docker >/dev/null 2>&1 || fail "docker not found (install docker first)"
docker compose version >/dev/null 2>&1 || fail "docker compose plugin not installed"
[ -f "$COMPOSE_SRC" ] || fail "missing $COMPOSE_SRC (run from a checked-out repo)"
[ -f "$UNIT_SRC" ] || fail "missing $UNIT_SRC"
[ -f "$UNIT_TMPL_SRC" ] || fail "missing $UNIT_TMPL_SRC"
[ -d "$VPSM_DATA" ] || fail "vps-manager data dir not found at $VPSM_DATA"
ok "docker present"
ok "vps-manager data dir: $VPSM_DATA"

bold "→ Creating directories"
mkdir -p "$DATA_DIR/sessions" "$DATA_DIR/media" "$DATA_DIR/files"
chmod 0700 "$DATA_DIR" "$DATA_DIR/sessions" "$DATA_DIR/media" "$DATA_DIR/files"
mkdir -p "$INSTALL_DIR"
ok "$DATA_DIR (0700)"
ok "$INSTALL_DIR"

bold "→ docker-compose.yml"
install -m 0644 "$COMPOSE_SRC" "$INSTALL_DIR/docker-compose.yml"
ok "$INSTALL_DIR/docker-compose.yml"

bold "→ Generating / preserving secrets"
ENV_FILE="$INSTALL_DIR/.env"
if [ -f "$ENV_FILE" ]; then
  ok "existing $ENV_FILE preserved (secrets unchanged)"
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi
: "${WAHA_API_KEY:=$(openssl rand -hex 32)}"
: "${WAHA_HMAC_SECRET:=$(openssl rand -hex 32)}"

umask 0177
cat > "$ENV_FILE" <<EOF
# Generated by scripts/whatsapp/install.sh. Do not edit by hand.
WAHA_API_KEY=${WAHA_API_KEY}
WAHA_HMAC_SECRET=${WAHA_HMAC_SECRET}
EOF
chmod 0600 "$ENV_FILE"
ok "$ENV_FILE (mode 0600)"

bold "→ Mirroring secrets into vps-manager vault"
# We can't decrypt the vault from a shell script (AES-GCM under JWT secret).
# The Go service writes a sidecar manifest at $VPSM_DATA/whatsapp/secrets.put
# which the next vps-manager startup ingests. Failsafe: also accept manual
# entry via the panel's Secrets UI.
mkdir -p "$VPSM_DATA/whatsapp"
chmod 0700 "$VPSM_DATA/whatsapp"
cat > "$VPSM_DATA/whatsapp/secrets.put" <<EOF
{"waha_api_key":"${WAHA_API_KEY}","waha_hmac_secret":"${WAHA_HMAC_SECRET}"}
EOF
chmod 0600 "$VPSM_DATA/whatsapp/secrets.put"
ok "$VPSM_DATA/whatsapp/secrets.put (consumed on next restart)"

bold "→ systemd units"
# Legacy single-tenant unit (v1) — desabilitada após MigrateV1ToV2.
install -m 0644 "$UNIT_SRC" "$UNIT_DST"
# Templated unit (v2 multi-tenant) — instâncias vpsm-whatsapp@<user>
# são enabled pelo Manager.Provision via Go ao criar cada user.
install -m 0644 "$UNIT_TMPL_SRC" "$UNIT_TMPL_DST"
systemctl daemon-reload
# Só habilita o legado se SchemaVersion < 2 (ou config inexistente).
# Pós-migração esta unit fica disabled; ignora silenciosamente se já passou.
if [ ! -f "$VPSM_DATA/config.json" ] || ! grep -q '"schema_version": 2' "$VPSM_DATA/config.json" 2>/dev/null; then
  systemctl enable vpsm-whatsapp.service >/dev/null 2>&1 || true
  ok "$UNIT_DST enabled (legacy v1 — pré-migração)"
else
  ok "$UNIT_DST installed (v2 ativo — legacy desabilitada)"
fi
ok "$UNIT_TMPL_DST installed (template multi-tenant)"

bold "→ Pulling WAHA image (may take a minute)"
( cd "$INSTALL_DIR" && docker compose pull --quiet ) && ok "image pulled" || warn "pull failed (will retry on first start)"

bold ""
bold "✅ Installation complete."
echo
echo "Next steps:"
echo "  1) Restart vps-manager so it ingests the secrets:"
echo "       systemctl restart vps-manager"
echo "  2) Open the panel and navigate to the WhatsApp tab."
echo "  3) Click \"Conectar\" — the QR will render in the UI."
echo "  4) Scan it from your phone (WhatsApp → Settings → Linked Devices)."
echo
echo "Operational:"
echo "  vpsmctl whatsapp status    — connection state from CLI"
echo "  vpsmctl whatsapp restart   — full container restart"
echo "  vpsmctl whatsapp logs      — tail WAHA container logs"
echo "  vpsmctl whatsapp logout    — unpair the device"
echo
