#!/usr/bin/env bash

set -euo pipefail

if [ "${EUID:-$(id -u)}" -ne 0 ]; then
  echo "this script must run as root" >&2
  exit 1
fi

REPO_DIR="${REPO_DIR:-/opt/panel}"
INSTALL_DIR="/opt/panel-whatsapp"
DATA_DIR="/var/lib/panel-whatsapp"
UNIT_DST="/etc/systemd/system/panel-whatsapp.service"
UNIT_TMPL_DST="/etc/systemd/system/panel-whatsapp@.service"
COMPOSE_SRC="${REPO_DIR}/scripts/whatsapp/docker-compose.yml"
UNIT_SRC="${REPO_DIR}/scripts/whatsapp/panel-whatsapp.service"
UNIT_TMPL_SRC="${REPO_DIR}/scripts/whatsapp/panel-whatsapp@.service"
PANEL_DATA="${PANEL_DATA:-/opt/panel/data}"
VAULT_HELPER="${REPO_DIR}/scripts/whatsapp/vault-put.sh"

bold() { printf "\033[1m%s\033[0m\n" "$*"; }
ok()   { printf "  ✓ %s\n" "$*"; }
warn() { printf "  ⚠ %s\n" "$*" >&2; }
fail() { printf "  ✗ %s\n" "$*" >&2; exit 1; }

bold "→ Checking prerequisites"
command -v docker >/dev/null 2>&1 || fail "docker not found (install docker first)"
docker compose version >/dev/null 2>&1 || fail "docker compose plugin not installed"
[ -f "$COMPOSE_SRC" ] || fail "missing $COMPOSE_SRC (run from a checked-out repo)"
[ -f "$UNIT_SRC" ] || fail "missing $UNIT_SRC"
[ -f "$UNIT_TMPL_SRC" ] || fail "missing $UNIT_TMPL_SRC"
[ -d "$PANEL_DATA" ] || fail "server-control-panel data dir not found at $PANEL_DATA"
ok "docker present"
ok "server-control-panel data dir: $PANEL_DATA"

bold "→ Creating directories"
mkdir -p "$DATA_DIR/sessions" "$DATA_DIR/media" "$DATA_DIR/files"
chmod 0700 "$DATA_DIR" "$DATA_DIR/sessions" "$DATA_DIR/media" "$DATA_DIR/files"
mkdir -p "$INSTALL_DIR"
ok "$DATA_DIR (0700)"
ok "$INSTALL_DIR"

bold "→ docker-compose.yml"
install -m 0644 "$COMPOSE_SRC" "$INSTALL_DIR/docker-compose.yml"
ok "$INSTALL_DIR/docker-compose.yml"

bold "→ Generating / preserving secrets"
ENV_FILE="$INSTALL_DIR/.env"
if [ -f "$ENV_FILE" ]; then
  ok "existing $ENV_FILE preserved (secrets unchanged)"
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi
: "${WAHA_API_KEY:=$(openssl rand -hex 32)}"
: "${WAHA_HMAC_SECRET:=$(openssl rand -hex 32)}"

umask 0177
cat > "$ENV_FILE" <<EOF
# Generated by scripts/whatsapp/install.sh. Do not edit by hand.
WAHA_API_KEY=${WAHA_API_KEY}
WAHA_HMAC_SECRET=${WAHA_HMAC_SECRET}
EOF
chmod 0600 "$ENV_FILE"
ok "$ENV_FILE (mode 0600)"

bold "→ Mirroring secrets into server-control-panel vault"
mkdir -p "$PANEL_DATA/whatsapp"
chmod 0700 "$PANEL_DATA/whatsapp"
cat > "$PANEL_DATA/whatsapp/secrets.put" <<EOF
{"waha_api_key":"${WAHA_API_KEY}","waha_hmac_secret":"${WAHA_HMAC_SECRET}"}
EOF
chmod 0600 "$PANEL_DATA/whatsapp/secrets.put"
ok "$PANEL_DATA/whatsapp/secrets.put (consumed on next restart)"

bold "→ systemd units"
install -m 0644 "$UNIT_SRC" "$UNIT_DST"
install -m 0644 "$UNIT_TMPL_SRC" "$UNIT_TMPL_DST"
systemctl daemon-reload
if [ ! -f "$PANEL_DATA/config.json" ] || ! grep -q '"schema_version": 2' "$PANEL_DATA/config.json" 2>/dev/null; then
  systemctl enable panel-whatsapp.service >/dev/null 2>&1 || true
  ok "$UNIT_DST enabled (legacy v1, pre-migration)"
else
  ok "$UNIT_DST installed (v2 active, legacy disabled)"
fi
ok "$UNIT_TMPL_DST installed (template multi-tenant)"

bold "→ Pulling WAHA image (may take a minute)"
( cd "$INSTALL_DIR" && docker compose pull --quiet ) && ok "image pulled" || warn "pull failed (will retry on first start)"

bold ""
bold "✅ Installation complete."
echo
echo "Next steps:"
echo "  1) Restart server-control-panel so it ingests the secrets:"
echo "       systemctl restart server-control-panel"
echo "  2) Open the panel and navigate to the WhatsApp tab."
echo "  3) Click \"Connect\" — the QR will render in the UI."
echo "  4) Scan it from your phone (WhatsApp → Settings → Linked Devices)."
echo
echo "Operational:"
echo "  panelctl whatsapp status    — connection state from CLI"
echo "  panelctl whatsapp restart   — full container restart"
echo "  panelctl whatsapp logs      — tail WAHA container logs"
echo "  panelctl whatsapp logout    — unpair the device"
echo
