// HTTP client for the mobile BFF (/api/mobile/v1), 100% generated by
// org.openapi.generator from openapi/mobile-v1.yaml — that file in turn
// is generated on the Go side (internal/mobilebff, `make mobile-openapi-spec`),
// never written by hand. A pure Kotlin/JVM module (no AGP): consumers run on
// any target (Android app, JVM tests) without depending on the Android SDK here.
//
// Generating the spec is an explicit developer/CI step (`make
// mobile-openapi-spec`), outside this build's dependency graph.
// The architectural decision behind huma/v2 is recorded separately.
// What THIS module guarantees is that, once the committed spec is updated,
// `openApiGenerate` regenerates the Kotlin client whenever the YAML content
// changes (normal Gradle input tracking).
plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.openapi.generator)
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

val generatedSrcDir = layout.buildDirectory.dir("generated/openapi")

openApiGenerate {
    generatorName.set("kotlin")
    inputSpec.set("$projectDir/openapi/mobile-v1.yaml")
    outputDir.set(generatedSrcDir)
    // openapi-templates/ overrides the generator's built-in kotlin-client/libraries/jvm-okhttp
    // templates with a single, surgical fix — see the comment at the top of
    // openapi-templates/libraries/jvm-okhttp/api.mustache for the compile error it prevents.
    // Files the generator doesn't find here fall back to its own built-in templates, so every
    // other endpoint's generated code is unaffected.
    templateDir.set("$projectDir/openapi-templates")
    packageName.set("com.vpsmanager.mobileapiclient")
    apiPackage.set("com.vpsmanager.mobileapiclient.api")
    modelPackage.set("com.vpsmanager.mobileapiclient.model")
    invokerPackage.set("com.vpsmanager.mobileapiclient.invoker")
    configOptions.set(
        mapOf(
            "library" to "jvm-okhttp4",
            "serializationLibrary" to "kotlinx_serialization",
            "dateLibrary" to "java8",
            "useCoroutines" to "true",
        )
    )
}

sourceSets {
    main {
        kotlin.srcDir(generatedSrcDir.map { it.dir("src/main/kotlin") })
    }
}

tasks.named("compileKotlin") {
    dependsOn("openApiGenerate")
}

dependencies {
    api(libs.okhttp)
    api(libs.kotlinx.serialization.json)
    // generatorName=kotlin with useCoroutines=true emits suspend funs that call
    // kotlinx.coroutines directly (withContext/Dispatchers/suspendCancellableCoroutine) —
    // a real dependency of the generated code, not an optional one.
    api(libs.kotlinx.coroutines.core)
}
