package dev.servercontrolpanel.designsystem

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal val PanelLightColors = lightColorScheme(
    primary = Color(0xFF006877),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFA1EFFF),
    onPrimaryContainer = Color(0xFF001F25),
    inversePrimary = Color(0xFF2FD9F4),
    secondary = Color(0xFF40646B),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFC2E9F2),
    onSecondaryContainer = Color(0xFF001F25),
    tertiary = Color(0xFF00668A),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFC4E7FF),
    onTertiaryContainer = Color(0xFF001E2C),
    error = Color(0xFFBF0323),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD5),
    onErrorContainer = Color(0xFF3D0600),
    background = Color(0xFFF4FBFC),
    onBackground = Color(0xFF171C1D),
    surface = Color(0xFFF4FBFC),
    onSurface = Color(0xFF171C1D),
    surfaceVariant = Color(0xFFD4E6EA),
    onSurfaceVariant = Color(0xFF3A494D),
    surfaceTint = Color(0xFF006877),
    inverseSurface = Color(0xFF2C3132),
    inverseOnSurface = Color(0xFFEBF2F3),
    outline = Color(0xFF6A7A7D),
    outlineVariant = Color(0xFFB8CACE),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFF4FBFC),
    surfaceDim = Color(0xFFD4DBDD),
    surfaceContainer = Color(0xFFE8EFF1),
    surfaceContainerHigh = Color(0xFFE3E9EB),
    surfaceContainerHighest = Color(0xFFDDE4E5),
    surfaceContainerLow = Color(0xFFEEF5F6),
    surfaceContainerLowest = Color(0xFFFFFFFF),
)

internal val PanelDarkColors = darkColorScheme(
    primary = Color(0xFF2FD9F4),
    onPrimary = Color(0xFF00363E),
    primaryContainer = Color(0xFF004E5A),
    onPrimaryContainer = Color(0xFFA1EFFF),
    inversePrimary = Color(0xFF006877),
    secondary = Color(0xFFA7CDD5),
    onSecondary = Color(0xFF0F353C),
    secondaryContainer = Color(0xFF284C53),
    onSecondaryContainer = Color(0xFFC2E9F2),
    tertiary = Color(0xFF7DD0FF),
    onTertiary = Color(0xFF003549),
    tertiaryContainer = Color(0xFF004C69),
    onTertiaryContainer = Color(0xFFC4E7FF),
    error = Color(0xFFFFB4AA),
    onError = Color(0xFF68000D),
    errorContainer = Color(0xFF930018),
    onErrorContainer = Color(0xFFFFDAD5),
    background = Color(0xFF0E1415),
    onBackground = Color(0xFFDDE4E5),
    surface = Color(0xFF0E1415),
    onSurface = Color(0xFFDDE4E5),
    surfaceVariant = Color(0xFF3A494D),
    onSurfaceVariant = Color(0xFFB8CACE),
    surfaceTint = Color(0xFF2FD9F4),
    inverseSurface = Color(0xFFDDE4E5),
    inverseOnSurface = Color(0xFF2C3132),
    outline = Color(0xFF839497),
    outlineVariant = Color(0xFF3A494D),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF343A3B),
    surfaceDim = Color(0xFF0E1415),
    surfaceContainer = Color(0xFF1B2022),
    surfaceContainerHigh = Color(0xFF262B2C),
    surfaceContainerHighest = Color(0xFF303637),
    surfaceContainerLow = Color(0xFF171C1D),
    surfaceContainerLowest = Color(0xFF080F11),
)

val AdaptiveIconBackground: Color = Color(0xFF00363E)

val MarkOnBackground: Color = Color(0xFF2FD9F4)
