package videocall

import (
	"errors"
	"log"
	"strings"
	"sync"
	"sync/atomic"
	"time"
)

// Hub is the in-memory signaling state machine. ZERO knowledge of WebSocket
// here — Hub.Forward / Broadcast / Join / Leave operate on abstract Peer
// handles. The WS handler in ws.go is a thin adapter that wires a real
// *websocket.Conn into a Peer.SendCh.
//
// This separation exists for testability: signaling logic (room state, ACL,
// glare handling) can be exercised with fake peers in plain Go tests.
type Hub struct {
	mu       sync.RWMutex
	peers    map[string]*Peer               // peer id -> peer
	byRoom   map[string]map[string]struct{} // room id -> set of peer ids
	rateMu   sync.Mutex
	rate     map[string]*rateBucket // peer id -> rate limiter
	maxPerRm int                    // hard cap on peers per room (mesh sanity)
}

// Peer is an abstract participant. SendCh is the egress queue: the WS
// adapter goroutine drains it and writes to the socket. Buffered so a slow
// network on one peer doesn't stall the hub.
type Peer struct {
	ID     string
	User   string
	RoomID string
	// ClientID is the STABLE identity of a client across WS reconnects.
	// Unlike ID (regenerated by randomID() on every upgrade), ClientID is
	// supplied by the client: a sessionStorage uuid for authed users, the
	// token jti for guests. Empty when the client predates this feature —
	// in that case the peer behaves exactly as before (no reconnect
	// eviction). Used by Join to evict the stale ghost of a reconnecting
	// client before the cap-check (fixes the phantom-peer duplication).
	ClientID string
	SendCh   chan SignalingMsg
	// closed is set when the peer is removed from the hub. Once closed, no
	// further messages will be sent on SendCh.
	closed chan struct{}
	// leaveAudited guarantees ONE videocall.leave line per peer. On SIGTERM
	// Service.Close drains the remaining peers (the defers of the hijacked WS
	// goroutines do not run — that is why the audit log had joins with no leave);
	// the CAS stops a late defer from auditing the same exit twice.
	leaveAudited atomic.Bool
}

// markLeaveAudited returns true for the FIRST caller — whoever wins, audits.
func (p *Peer) markLeaveAudited() bool {
	if p == nil {
		return false
	}
	return p.leaveAudited.CompareAndSwap(false, true)
}

type rateBucket struct {
	tokens int
	last   time.Time
}

// NewHub creates an empty signaling hub. maxPerRoom defaults to 4 (the
// architecturally documented mesh-P2P ceiling).
func NewHub(maxPerRoom int) *Hub {
	if maxPerRoom <= 0 {
		maxPerRoom = 4
	}
	return &Hub{
		peers:    make(map[string]*Peer),
		byRoom:   make(map[string]map[string]struct{}),
		rate:     make(map[string]*rateBucket),
		maxPerRm: maxPerRoom,
	}
}

// Errors surfaced by Hub. Kept exported so handlers can translate to HTTP
// status codes (room-full → 409, ACL violation → 403, etc.).
var (
	ErrRoomFull        = errors.New("room is full")
	ErrPeerNotInRoom   = errors.New("peer not in any room")
	ErrTargetNotInRoom = errors.New("target peer is not in the same room")
	ErrTargetUnknown   = errors.New("target peer not connected")
	ErrRateLimited     = errors.New("rate limit exceeded")
	// ErrAlreadyJoined signals that the same user is already connected to the
	// room from another tab/session. It avoids mutual echo and needless slot
	// consumption in the mesh cap=4. The HTTP handler maps it to 409 + a PT-BR message.
	ErrAlreadyJoined = errors.New("user already in room")
)

// Join registers a peer in a room and returns the existing peers for the
// snapshot the client uses to seed RTCPeerConnection setup. After Join, the
// hub broadcasts a peer-joined message to the existing peers.
//
// The returned peers list does NOT include `p` itself.
func (h *Hub) Join(p *Peer) ([]PeerInfo, error) {
	if p.RoomID == "" || p.ID == "" {
		return nil, errors.New("peer missing id or room")
	}
	h.mu.Lock()
	defer h.mu.Unlock()
	set, ok := h.byRoom[p.RoomID]
	if !ok {
		set = make(map[string]struct{})
		h.byRoom[p.RoomID] = set
	}
	// Root fix: ghost eviction on reconnect. On an abrupt drop the old peer
	// only leaves via the pong timeout (≤45s); meanwhile the same client
	// reconnects with a NEW peer.ID (randomID), becoming a duplicate tile
	// (guest) or hitting ErrAlreadyJoined/ErrRoomFull (auth). If an existing
	// peer carries the SAME non-empty ClientID, it is the ghost of that
	// client's previous connection — evict it BEFORE the cap-check so the
	// reconnect into a room "full of nothing but ghosts" does not fail. We
	// collect the ids first and only then evict (evictLocked mutates `set`).
	if p.ClientID != "" {
		var ghosts []string
		for id := range set {
			if old, ok := h.peers[id]; ok && old.ClientID == p.ClientID {
				ghosts = append(ghosts, id)
			}
		}
		for _, id := range ghosts {
			log.Printf("videocall: evicting ghost peer id=%s clientID=%s room=%s (reconnect by new peer id=%s)", id, p.ClientID, p.RoomID, p.ID)
			h.evictLocked(id, set)
		}
	}
	if len(set) >= h.maxPerRm {
		return nil, ErrRoomFull
	}
	// Detects the same account in 2 tabs. user="guest:<name>" can repeat
	// (several guests with the same name), so this only applies to
	// authenticated users (no "guest:" prefix). Avoids mutual echo + a wasted slot.
	if p.User != "" && !strings.HasPrefix(p.User, "guest:") {
		for id := range set {
			if other, ok := h.peers[id]; ok && other.User == p.User {
				return nil, ErrAlreadyJoined
			}
		}
	}
	// Snapshot existing peers BEFORE adding the new one.
	existing := make([]PeerInfo, 0, len(set))
	for id := range set {
		if other, ok := h.peers[id]; ok {
			existing = append(existing, PeerInfo{ID: other.ID, User: other.User, ClientID: other.ClientID})
		}
	}
	h.peers[p.ID] = p
	set[p.ID] = struct{}{}
	// Notify existing peers (under lock — message is queued non-blocking, so
	// safe). Doing this inside the lock avoids the race where two peers join
	// simultaneously and miss each other's notification.
	for id := range set {
		if id == p.ID {
			continue
		}
		other := h.peers[id]
		h.deliver(other, SignalingMsg{
			Type:    "peer-joined",
			From:    p.ID,
			Payload: mustJSON(PeerInfo{ID: p.ID, User: p.User, ClientID: p.ClientID}),
		})
	}
	return existing, nil
}

// Leave removes the peer and broadcasts peer-left to the rest of the room.
// Safe to call multiple times; second call is a no-op.
func (h *Hub) Leave(peerID string) {
	h.mu.Lock()
	defer h.mu.Unlock()
	p, ok := h.peers[peerID]
	if !ok {
		return
	}
	delete(h.peers, peerID)
	if set, ok := h.byRoom[p.RoomID]; ok {
		delete(set, peerID)
		if len(set) == 0 {
			delete(h.byRoom, p.RoomID)
		}
		for id := range set {
			other := h.peers[id]
			h.deliver(other, SignalingMsg{Type: "peer-left", From: peerID})
		}
	}
	// Signal the WS adapter goroutine to wrap up. Closing SendCh from the
	// hub side is the producer's contract — the consumer (writer) handles it.
	close(p.closed)
}

// OccupiedRooms lists the rooms with at least one connected peer. Used by the
// call session heartbeat to renew LastActiveAt.
func (h *Hub) OccupiedRooms() []string {
	h.mu.RLock()
	defer h.mu.RUnlock()
	out := make([]string, 0, len(h.byRoom))
	for room, set := range h.byRoom {
		if len(set) > 0 {
			out = append(out, room)
		}
	}
	return out
}

// PeerSnapshot is the (user, room) pair of a connected peer — the minimum the
// shutdown needs to close the audit log correctly.
type PeerSnapshot struct {
	Peer   *Peer
	User   string
	RoomID string
}

// SnapshotPeers returns every connected peer. Used only by the shutdown.
func (h *Hub) SnapshotPeers() []PeerSnapshot {
	h.mu.RLock()
	defer h.mu.RUnlock()
	out := make([]PeerSnapshot, 0, len(h.peers))
	for _, p := range h.peers {
		out = append(out, PeerSnapshot{Peer: p, User: p.User, RoomID: p.RoomID})
	}
	return out
}

// evictLocked removes a peer from the hub WITHOUT acquiring h.mu — the caller
// MUST already hold h.mu (write lock). It is the lock-free sibling of Leave, used
// by Join to take down the ghost of a client that is reconnecting (same ClientID).
//
// CRITICAL ORDER: delete(peers/set) BEFORE close(p.closed). The old reader of the
// evicted socket will run its late `defer Hub.Leave(oldID)` when the read deadline
// expires; with the delete already done, that Leave falls into the early return
// (peers[id] absent) and does NOT double-close p.closed. Inverting the order =
// panic "close of closed channel". It does not call Leave (non-reentrant under h.mu).
//
// Unlike Leave, it does NOT delete an empty byRoom[room]: evictLocked only runs
// inside Join, which repopulates the set with the new peer right afterwards.
func (h *Hub) evictLocked(peerID string, set map[string]struct{}) {
	p, ok := h.peers[peerID]
	if !ok {
		return
	}
	delete(h.peers, peerID)
	delete(set, peerID)
	// Tell the remaining peers the ghost left (its tile disappears on the front end).
	for id := range set {
		if other, ok := h.peers[id]; ok {
			h.deliver(other, SignalingMsg{Type: "peer-left", From: peerID})
		}
	}
	close(p.closed)
	// cleanupRate uses rateMu (not h.mu) — safe under the current lock.
	h.cleanupRate(peerID)
}

// Disconnect forces a peer out. Used for "kick by owner". It deduplicates with
// Leave: if the peer has already left, it is a no-op. It does not close the
// WebSocket directly — it only fires the closed channel; runWSLoop terminates on
// detecting peer.closed, and conn is closed via a defer in the caller.
func (h *Hub) Disconnect(peerID string) {
	h.mu.RLock()
	_, exists := h.peers[peerID]
	h.mu.RUnlock()
	if !exists {
		return
	}
	h.Leave(peerID)
}

// Forward routes a peer-to-peer message (offer/answer/ice/chat) to the
// target. Enforces three rules:
//
//  1. `from` must be a known peer.
//  2. `to` must be a known peer in the SAME room as `from` (ACL).
//  3. The sender's rate bucket must have tokens (50 msg/sec sliding).
//
// All three rules together close the "peer-A injects offer to peer-B in
// another room" attack vector.
func (h *Hub) Forward(fromID string, msg SignalingMsg) error {
	if !h.allowMsg(fromID) {
		return ErrRateLimited
	}
	h.mu.RLock()
	defer h.mu.RUnlock()
	from, ok := h.peers[fromID]
	if !ok {
		return ErrPeerNotInRoom
	}
	to, ok := h.peers[msg.To]
	if !ok {
		return ErrTargetUnknown
	}
	if to.RoomID != from.RoomID {
		return ErrTargetNotInRoom
	}
	// Stamp the From field server-side. We do NOT trust whatever the client
	// sent — an attacker could forge a different peer id otherwise.
	msg.From = fromID
	h.deliver(to, msg)
	return nil
}

// Broadcast sends `msg` to every peer in `from`'s room except `from` itself.
// Used for room-level state changes (someone toggled their camera, started
// screen share, etc.).
func (h *Hub) Broadcast(fromID string, msg SignalingMsg) error {
	if !h.allowMsg(fromID) {
		return ErrRateLimited
	}
	h.mu.RLock()
	defer h.mu.RUnlock()
	from, ok := h.peers[fromID]
	if !ok {
		return ErrPeerNotInRoom
	}
	msg.From = fromID
	set, ok := h.byRoom[from.RoomID]
	if !ok {
		return nil
	}
	for id := range set {
		if id == fromID {
			continue
		}
		other := h.peers[id]
		h.deliver(other, msg)
	}
	return nil
}

// PeersInRoom returns the snapshot of peer ids currently in `roomID`.
// Used by tests and the optional admin endpoint.
func (h *Hub) PeersInRoom(roomID string) []string {
	h.mu.RLock()
	defer h.mu.RUnlock()
	set := h.byRoom[roomID]
	out := make([]string, 0, len(set))
	for id := range set {
		out = append(out, id)
	}
	return out
}

// PeerUser returns the username associated with a peer id, or ("", false)
// if the peer is unknown.
func (h *Hub) PeerUser(peerID string) (string, bool) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	p, ok := h.peers[peerID]
	if !ok {
		return "", false
	}
	return p.User, true
}

// KickPeer forces a peer out of the room. Best-effort, it delivers a synthetic
// `kicked` message before the Leave (the client shows the reason).
// It returns (user, true) if the peer existed, ("", false) otherwise.
//
// The caller (the HTTP handler) must validate authorization (owner-only) first.
func (h *Hub) KickPeer(peerID, reason string) (string, bool) {
	h.mu.RLock()
	p, ok := h.peers[peerID]
	h.mu.RUnlock()
	if !ok {
		return "", false
	}
	user := p.User
	// Notify; deliver is non-blocking — best-effort. Right after, Leave closes.
	h.deliver(p, SignalingMsg{Type: "kicked", Error: reason})
	// FIX: a synchronous time.Sleep blocked the owner's HTTP handler for 50ms.
	// AfterFunc schedules the Leave in the background — the handler returns at once.
	time.AfterFunc(50*time.Millisecond, func() {
		h.Leave(peerID)
	})
	return user, true
}

// PeersInRoomWithUser returns [{id, user}] for every peer in a room. Needed for
// the kick: the handler validates that the target peer is in the owner's room.
func (h *Hub) PeersInRoomWithUser(roomID string) []PeerInfo {
	h.mu.RLock()
	defer h.mu.RUnlock()
	set := h.byRoom[roomID]
	out := make([]PeerInfo, 0, len(set))
	for id := range set {
		if p := h.peers[id]; p != nil {
			out = append(out, PeerInfo{ID: p.ID, User: p.User, ClientID: p.ClientID})
		}
	}
	return out
}

// deliver pushes a message into a peer's SendCh non-blocking. A full queue
// means the peer's WS writer is stalled (slow network, frozen tab) — we drop
// rather than back-pressure the hub. The peer's connection will time out via
// the WS pong handler and the cleanup will run Leave().
func (h *Hub) deliver(p *Peer, msg SignalingMsg) {
	if p == nil {
		return
	}
	select {
	case <-p.closed:
		return
	case p.SendCh <- msg:
	default:
		// Drop. Sustained drops are a symptom; the peer will be evicted by
		// the pong timeout in the WS adapter.
	}
}

// allowMsg implements a simple token-bucket rate limit per peer. 50 msgs/s
// burst, refills at 50/s. Picked to comfortably cover real signaling traffic
// (10-20 ICE candidates in the first second is normal) without letting a
// rogue peer flood the room.
const (
	rateBurst   = 50
	rateRefill  = 50 // per second
	rateMinStep = 20 * time.Millisecond
)

func (h *Hub) allowMsg(peerID string) bool {
	h.rateMu.Lock()
	defer h.rateMu.Unlock()
	now := time.Now()
	b, ok := h.rate[peerID]
	if !ok {
		b = &rateBucket{tokens: rateBurst, last: now}
		h.rate[peerID] = b
	}
	dt := now.Sub(b.last)
	if dt > rateMinStep {
		add := int(dt.Seconds() * float64(rateRefill))
		if add > 0 {
			b.tokens += add
			if b.tokens > rateBurst {
				b.tokens = rateBurst
			}
			b.last = now
		}
	}
	if b.tokens <= 0 {
		return false
	}
	b.tokens--
	return true
}

// cleanupRate drops rate buckets for peers that left. Called from Leave's
// caller path indirectly — kept O(1) per peer-leave to avoid map scan.
func (h *Hub) cleanupRate(peerID string) {
	h.rateMu.Lock()
	delete(h.rate, peerID)
	h.rateMu.Unlock()
}
