# libhpatchz.so: the PATCHER side of HDiffPatch (MIT), only what the device
# needs to APPLY a patch. The generator (hdiffz) runs on the server.
#
# Adapted copy of vendor/HDiffPatch/builds/android_ndk_jni_mk/Android.mk
# (commit pinned in ../../../toolchain.properties). Deliberately not ported to
# CMake: the -D flags decide which decompressors and checksums exist in the
# .so, and a lost -D does not break the build, it yields a .so that rejects
# patches at runtime on the user's device.
#
# Deliberate differences from upstream:
#   - HDP_PATH points at the vendored tree in ../../../vendor;
#   - the switches are fixed values (below), not command-line variables: this
#     .so has ONE configuration, the one vendor-files.txt covers;
#   - branches for disabled features are REMOVED, since their sources are not
#     vendored. Re-enabling one requires re-vendoring (vendor-hdiffpatch.sh --relist);
#   - the armeabi-v7a branch is gone: we ship arm64-v8a and x86_64.

LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := hpatchz

HDP_PATH := $(LOCAL_PATH)/../../../vendor/HDiffPatch

# Switches (same names as upstream so the files stay comparable):
#
#   MT     = 1  multithreaded I/O and decompression. ApkPatcher uses
#               threadNum=1, but window diffs (-WD) only parallelize with this
#               code present. Disabling would save about 10 KB.
#   ZLIB   = 1  deflate via -lz (Android's own libz.so, no zlib sources
#               vendored). Also enables the crc32 checksum.
#   LZMA   = 1  hdiffz -c-lzma / -c-lzma2.
#   ZSTD   = 1  hdiffz -c-zstd, the DEFAULT hdiffz compressor.
#   MD5    = 1  } checksum plugins. We verify with SHA-256 in Kotlin, but the
#   XXH    = 1  } generator lives elsewhere and -C-md5 or -C-xxh128 would fail
#               on device with HPATCH_CHECKSUMSET_ERROR. Measured cost of both:
#               10,264 bytes in the arm64 .so.
#
#   BROTLI = 0  never generated by this project.
#   VCD    = 0  VCDIFF format, out of scope (patches come from our hdiffz).
#   BSD    = 0  bsdiff4/endsley format, same reason (upstream also needs BZIP2).
#   BZIP2  = 0  only needed by BSD.
#   DIR    = 0  directory patch. The target here is a single file (the APK).

DEF_FLAGS := -Os -flto -DANDROID_NDK -DNDEBUG -D_LARGEFILE_SOURCE \
             -D_IS_NEED_DEFAULT_CompressPlugin=0 \
             -D_IS_NEED_CACHE_OLD_BY_COVERS=0 \
             -D_IS_NEED_CACHE_OLD_ALL=1
LINK_FLAGS := -llog

# With _IS_NEED_CACHE_OLD_ALL=1 (from upstream), a cacheMemory >= the old APK
# size makes the patcher load the WHOLE old file into native memory. That is
# why the value in ApkPatcher.kt matters (see DEFAULT_CACHE_MEMORY_BYTES).

# Disabled features: the -D flags must exist even without sources, because
# hpatchz.c branches on them.
DEF_FLAGS += -D_IS_NEED_BSDIFF=0 -D_IS_NEED_VCDIFF=0 -D_IS_NEED_DIR_DIFF_PATCH=0

Src_Files := $(HDP_PATH)/builds/android_ndk_jni_mk/hpatch_jni.c \
             $(HDP_PATH)/builds/android_ndk_jni_mk/hpatch.c \
             $(HDP_PATH)/file_for_patch.c \
             $(HDP_PATH)/libHDiffPatch/HPatch/patch.c

# MT = 1
DEF_FLAGS += -D_IS_USED_MULTITHREAD=1
Src_Files += $(HDP_PATH)/libHDiffPatch/HPatch/hpatch_mt/_hcache_old_mt.c \
             $(HDP_PATH)/libHDiffPatch/HPatch/hpatch_mt/_hcache_window_old_mt.c \
             $(HDP_PATH)/libHDiffPatch/HPatch/hpatch_mt/_hinput_mt.c \
             $(HDP_PATH)/libHDiffPatch/HPatch/hpatch_mt/_houtput_mt.c \
             $(HDP_PATH)/libHDiffPatch/HPatch/hpatch_mt/_hpatch_mt.c \
             $(HDP_PATH)/libHDiffPatch/HPatch/hpatch_mt/hpatch_mt.c \
             $(HDP_PATH)/libParallel/parallel_import_c.c

# Checksums: fadler64 (hdiffz default), crc32 (free with system zlib), md5 and
# xxh3/xxh128 for the reasons above.
DEF_FLAGS += -D_IS_NEED_DEFAULT_ChecksumPlugin=0 -D_ChecksumPlugin_fadler64
Src_Files += $(HDP_PATH)/libHDiffPatch/HDiff/private_diff/limit_mem_diff/adler_roll.c

DEF_FLAGS += -D_ChecksumPlugin_crc32

MD5_PATH  := $(HDP_PATH)/../libmd5
DEF_FLAGS += -D_ChecksumPlugin_md5 -I$(MD5_PATH)
Src_Files += $(MD5_PATH)/md5.c

XXH_PATH  := $(HDP_PATH)/../xxHash
DEF_FLAGS += -D_ChecksumPlugin_xxh3 -D_ChecksumPlugin_xxh128 -I$(XXH_PATH)

# ZLIB = 1: deflate against the system libz; no zlib sources are vendored.
DEF_FLAGS += -D_CompressPlugin_zlib
LINK_FLAGS += -lz

# LZMA = 1
LZMA_PATH := $(HDP_PATH)/../lzma/C
DEF_FLAGS += -D_CompressPlugin_lzma -D_CompressPlugin_lzma2 -DZ7_ST -I$(LZMA_PATH)
Src_Files += $(LZMA_PATH)/LzmaDec.c \
             $(LZMA_PATH)/Lzma2Dec.c
ifeq ($(TARGET_ARCH_ABI),arm64-v8a)
  # arm64 assembly LZMA decoder: the path real devices run (x86_64 is emulator only).
  DEF_FLAGS += -DZ7_LZMA_DEC_OPT
  Src_Files += $(LZMA_PATH)/../Asm/arm64/LzmaDecOpt.S
endif

# ZSTD = 1: decompression side only (lib/decompress + lib/common).
ZSTD_PATH := $(HDP_PATH)/../zstd/lib
DEF_FLAGS += -D_CompressPlugin_zstd -I$(ZSTD_PATH) -I$(ZSTD_PATH)/common -I$(ZSTD_PATH)/decompress \
             -DZSTD_HAVE_WEAK_SYMBOLS=0 -DZSTD_TRACE=0 -DZSTD_DISABLE_ASM=1 -DZSTDLIB_HIDDEN= \
             -DZSTDLIB_VISIBLE= -DZDICTLIB_VISIBLE= -DZSTDERRORLIB_VISIBLE= \
             -DDYNAMIC_BMI2=0 -DZSTD_LEGACY_SUPPORT=0 -DZSTD_LIB_DEPRECATED=0 -DHUF_FORCE_DECOMPRESS_X1=1 \
             -DZSTD_FORCE_DECOMPRESS_SEQUENCES_SHORT=1 -DZSTD_NO_INLINE=1 -DZSTD_STRIP_ERROR_STRINGS=1 \
             -DZSTDERRORLIB_VISIBILITY=
Src_Files += $(ZSTD_PATH)/common/debug.c \
             $(ZSTD_PATH)/common/entropy_common.c \
             $(ZSTD_PATH)/common/error_private.c \
             $(ZSTD_PATH)/common/fse_decompress.c \
             $(ZSTD_PATH)/common/xxhash.c \
             $(ZSTD_PATH)/common/zstd_common.c \
             $(ZSTD_PATH)/decompress/huf_decompress.c \
             $(ZSTD_PATH)/decompress/zstd_ddict.c \
             $(ZSTD_PATH)/decompress/zstd_decompress.c \
             $(ZSTD_PATH)/decompress/zstd_decompress_block.c

LOCAL_SRC_FILES := $(Src_Files)
LOCAL_LDLIBS    := $(LINK_FLAGS)
LOCAL_CFLAGS    := $(DEF_FLAGS)
include $(BUILD_SHARED_LIBRARY)
