package com.vpsmanager.patchengine

import android.os.Debug
import android.util.Log
import androidx.test.platform.app.InstrumentationRegistry
import java.io.File
import java.util.Properties
import java.util.concurrent.TimeUnit
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test

/**
 * **The proof that matters.** A real cycle, on a device/emulator:
 *
 *  1. signed 0.1.5 release APK (the already-installed "base");
 *  2. the HDiffPatch 0.1.5 -> 0.1.6 patch generated by the same `hdiffz` the
 *     server will run;
 *  3. apply;
 *  4. assert that the SHA-256 of what came out is **identical** to that of the
 *     signed 0.1.6 APK.
 *
 * If this passes, the central risk of the incremental update is gone: the
 * bytes rebuilt on the phone are the same ones Android's installer will verify
 * against the signature. If it fails, no update banner should be written
 * before understanding why.
 *
 * ### The fixtures are not versioned — and this test FAILS without them
 * `base.apk` alone is ~33 MB. With the patch it would be ~66 MB of opaque
 * binary living forever in the repository to prove something that
 * `tools/make-patch-fixtures.sh` rebuilds in ~4 minutes from source. The
 * choice was to generate on demand.
 *
 * The price is this test failing with "fixtures missing" on a clean checkout.
 * That is deliberate: `assumeTrue`/skip would leave the suite green without
 * the central proof, which is the worst possible outcome for a module whose
 * only reason to exist is that proof. Run:
 *
 * ```
 * android/patch-engine/tools/make-patch-fixtures.sh
 * ```
 *
 * The 0.1.6 APK itself does NOT go into the assets: the test does not need it,
 * it needs the hash it ought to have — 64 characters instead of 33 MB.
 */
class ApkPatcherRealApkTest {

    private companion object {
        const val TAG = "PatchEngineRealApk"
        const val BASE_ASSET = "patch-fixtures/base.apk"
        const val PATCH_ASSET = "patch-fixtures/update.hdiff"
        const val EXPECTED_ASSET = "patch-fixtures/expected.properties"

        /**
         * Ceiling on the PEAK native heap during the patch.
         *
         * A lock against a specific regression: with `_IS_NEED_CACHE_OLD_ALL=1`
         * in `Android.mk`, raising `DEFAULT_CACHE_MEMORY_BYTES` to a value
         * greater than or equal to the old APK makes the patcher load all
         * ~33 MB into memory.
         *
         * It has to be the PEAK, and by sampling: measuring only before and
         * after sees nothing, because `hpatchz` frees everything before
         * returning (the before/after delta measured here came to 144 bytes).
         * 16 MiB leaves comfortable headroom over the ~8.8 MB measured with a
         * 4 MiB cache and still catches a jump to 33 MB.
         */
        const val NATIVE_HEAP_PEAK_CEILING_BYTES = 16L * 1024 * 1024

        /** Peak sampling interval — the whole patch takes ~100 ms on the emulator. */
        const val HEAP_SAMPLE_INTERVAL_MS = 2L
    }

    private lateinit var dir: File

    @Before
    fun setUp() {
        // The directory is created BEFORE the fixture check on purpose: if the
        // check failed first, `tearDown` would blow up with
        // UninitializedPropertyAccessException and that exception is the one
        // JUnit would report — hiding exactly the message that says what to do.
        dir = File(
            InstrumentationRegistry.getInstrumentation().targetContext.cacheDir,
            "realapk-${System.nanoTime()}",
        ).apply { mkdirs() }

        assertTrue(
            "fixtures ausentes — rode android/patch-engine/tools/make-patch-fixtures.sh " +
                "(elas não são versionadas: ~66 MB regeneráveis em ~4 min; ver o KDoc desta classe)",
            PatchFixtures.exists(BASE_ASSET) &&
                PatchFixtures.exists(PATCH_ASSET) &&
                PatchFixtures.exists(EXPECTED_ASSET),
        )
    }

    @After
    fun tearDown() {
        if (::dir.isInitialized) dir.deleteRecursively()
    }

    @Test
    fun patch015Para016_reconstroiOApkAssinadoByteAByte() {
        val expectedProps = Properties().apply {
            InstrumentationRegistry.getInstrumentation().context.assets.open(EXPECTED_ASSET).use { load(it) }
        }
        val expectedSha = expectedProps.getProperty("newSha256")
        val expectedSize = expectedProps.getProperty("newSizeBytes").toLong()

        val base = PatchFixtures.copyOut(BASE_ASSET, dir, "base.apk")
        val patch = PatchFixtures.copyOut(PATCH_ASSET, dir, "update.hdiff")
        val out = File(dir, "vpsmanager-0.1.6.apk")

        // A sanity check on the fixture itself: if the base was corrupted on its
        // way out of the asset, the test has to say so, not blame the patcher.
        assertEquals(
            "base.apk saiu do asset diferente do que entrou",
            expectedProps.getProperty("oldSha256"),
            ApkPatcher.sha256Of(base),
        )

        val heapBefore = Debug.getNativeHeapAllocatedSize()
        val peakSampler = HeapPeakSampler(heapBefore).also { it.start() }
        val startedAt = System.nanoTime()

        val result = ApkPatcher().apply(base, patch, out, ExpectedApk(expectedSha, expectedSize))

        val elapsedMs = (System.nanoTime() - startedAt) / 1_000_000
        val heapPeakGrowth = peakSampler.stopAndPeakGrowth()

        Log.i(
            TAG,
            "base=${base.length()}B patch=${patch.length()}B " +
                "(${"%.2f".format(patch.length() * 100.0 / base.length())}% do APK) " +
                "tempo=${elapsedMs}ms picoHeapNativo+=${heapPeakGrowth}B " +
                "amostras=${peakSampler.sampleCount} resultado=$result",
        )

        assertTrue("esperava Applied, veio $result", result is PatchResult.Applied)
        result as PatchResult.Applied
        assertEquals("o APK reconstruído tem que ser byte a byte o 0.1.6 assinado", expectedSha, result.sha256)
        assertEquals(expectedSize, out.length())

        assertTrue(
            "pico de heap nativo em ${heapPeakGrowth}B (${peakSampler.sampleCount} amostras) — " +
                "alguém aumentou o cacheMemory? com _IS_NEED_CACHE_OLD_ALL=1 isso passa a " +
                "carregar o APK velho inteiro na RAM",
            heapPeakGrowth < NATIVE_HEAP_PEAK_CEILING_BYTES,
        )
    }

    /**
     * Samples `Debug.getNativeHeapAllocatedSize()` on a parallel thread to
     * estimate the PEAK — `hpatchz` gives all the memory back before
     * returning, and a before/after measurement around `apply` shows
     * practically zero.
     */
    private class HeapPeakSampler(private val baseline: Long) : Thread() {
        @Volatile private var running = true

        @Volatile private var peak = baseline

        @Volatile var sampleCount = 0
            private set

        override fun run() {
            while (running) {
                val now = Debug.getNativeHeapAllocatedSize()
                if (now > peak) peak = now
                sampleCount++
                try {
                    sleep(HEAP_SAMPLE_INTERVAL_MS)
                } catch (_: InterruptedException) {
                    return
                }
            }
        }

        fun stopAndPeakGrowth(): Long {
            running = false
            join(TimeUnit.SECONDS.toMillis(2))
            return peak - baseline
        }
    }

    @Test
    fun patchDoApkReal_sobreBaseErrada_naoEntregaArquivo() {
        val expectedProps = Properties().apply {
            InstrumentationRegistry.getInstrumentation().context.assets.open(EXPECTED_ASSET).use { load(it) }
        }
        val base = PatchFixtures.copyOut(BASE_ASSET, dir, "base.apk")
        val patch = PatchFixtures.copyOut(PATCH_ASSET, dir, "update.hdiff")

        // An "almost right" base: same size, a few bytes swapped. It is the
        // most dangerous shape of error, because everything in the diff header
        // still checks out.
        val wrongBase = File(dir, "wrong-base.apk").apply {
            val bytes = base.readBytes()
            for (i in bytes.indices step 1_000_000) bytes[i] = (bytes[i] + 1).toByte()
            writeBytes(bytes)
        }
        val out = File(dir, "out.apk")

        val result = ApkPatcher().apply(
            wrongBase,
            patch,
            out,
            ExpectedApk(
                expectedProps.getProperty("newSha256"),
                expectedProps.getProperty("newSizeBytes").toLong(),
            ),
        )

        assertTrue("um APK errado nunca pode virar Applied; veio $result", result !is PatchResult.Applied)
        assertTrue("o arquivo reprovado não pode ficar no disco", !out.exists())
    }
}
