package com.vpsmanager.patchengine

import androidx.test.platform.app.InstrumentationRegistry
import java.io.File
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test

/**
 * Instrumented — requires the real `libhpatchz.so` loaded on a device or
 * emulator. Runs against the SMALL versioned fixtures
 * (`src/androidTest/assets/hdiff`, 270 KB), so it works on a clean checkout,
 * without depending on `tools/make-patch-fixtures.sh`.
 *
 * The project's central proof is `ApkPatcherRealApkTest` (APK 0.1.5 -> 0.1.6).
 * This class covers what that one does not: the FAILURE paths. And the finding
 * that matters most is in [baseErrada_...] and [patchCorrompidoNoMeio_...]:
 * measured on `hpatchz`, a patch applied over a wrong base of the same size,
 * or a patch with one byte swapped in the middle of the compressed data,
 * **returns success** and writes a whole, wrong file. If this module trusted
 * the return code, it would hand that file to the installer. The two tests
 * below end in [PatchResult.IntegrityMismatch] — a result only reachable AFTER
 * the native side has said "ok" — which is the proof that the SHA-256 is what
 * holds.
 */
class ApkPatcherSmokeTest {

    // Generated by tools/make-smoke-fixtures.sh from the same fixed seed.
    // When regenerating the fixtures, the script prints this value to update here.
    private val expectedNewSha256 = "4cacda8517f06e47973f6b7450e27212728da54f880d34523948c8346ffbd2ae"
    private val expectedNewSize = 270_336L
    private val expected get() = ExpectedApk(expectedNewSha256, expectedNewSize)

    private lateinit var dir: File
    private lateinit var oldFile: File
    private lateinit var patchFile: File
    private lateinit var out: File

    private val patcher = ApkPatcher()

    @Before
    fun setUp() {
        dir = File(
            InstrumentationRegistry.getInstrumentation().targetContext.cacheDir,
            "smoke-${System.nanoTime()}",
        ).apply { mkdirs() }
        oldFile = PatchFixtures.copyOut("hdiff/smoke-old.bin", dir)
        patchFile = PatchFixtures.copyOut("hdiff/smoke.hdiff", dir)
        out = File(dir, "out.bin")
    }

    @After
    fun tearDown() {
        dir.deleteRecursively()
    }

    @Test
    fun aplicaOPatchEConfereOHash() {
        val result = patcher.apply(oldFile, patchFile, out, expected)

        assertTrue("esperava Applied, veio $result", result is PatchResult.Applied)
        result as PatchResult.Applied
        assertEquals(expectedNewSha256, result.sha256)
        assertEquals(expectedNewSize, out.length())
    }

    @Test
    fun baseErrada_oNativoAprovaMasOHashReprova() {
        // Same SIZE as the correct base, different content: the case where
        // hpatchz has no way to notice anything — the diff header checks out.
        val wrongBase = File(dir, "wrong-old.bin").apply {
            val bytes = oldFile.readBytes()
            for (i in bytes.indices step 4096) bytes[i] = (bytes[i] + 1).toByte()
            writeBytes(bytes)
        }

        val result = patcher.apply(wrongBase, patchFile, out, expected)

        assertTrue(
            "esperava IntegrityMismatch (o nativo teria devolvido 0 aqui), veio $result",
            result is PatchResult.IntegrityMismatch,
        )
        result as PatchResult.IntegrityMismatch
        assertEquals(expectedNewSha256, result.expectedSha256)
        assertFalse("hash divergente e arquivo no disco não podem coexistir", out.exists())
    }

    @Test
    fun patchCorrompidoNoMeio_oNativoAprovaMasOHashReprova() {
        val corrupt = PatchFixtures.corruptedCopy(patchFile, dir, "corrupt.hdiff", offset = 5_000)

        val result = patcher.apply(oldFile, corrupt, out, expected)

        assertTrue(
            "esperava IntegrityMismatch — um byte trocado no meio do zstd não faz o hpatchz falhar; veio $result",
            result is PatchResult.IntegrityMismatch,
        )
        assertFalse(out.exists())
    }

    @Test
    fun patchTruncado_falhaNoNativo() {
        val truncated = PatchFixtures.truncatedCopy(patchFile, dir, "trunc.hdiff", keepBytes = 4_000)

        val result = patcher.apply(oldFile, truncated, out, expected)

        assertTrue("esperava NativeFailure, veio $result", result is PatchResult.NativeFailure)
        assertEquals(HPatchCode.HPATCH_ERROR, (result as PatchResult.NativeFailure).code)
        assertFalse(out.exists())
    }

    @Test
    fun cabecalhoDestruido_falhaComoHdiffInfoError() {
        val broken = File(dir, "hdr.hdiff").apply {
            val bytes = patchFile.readBytes()
            for (i in 2 until 10) bytes[i] = 'Z'.code.toByte()
            writeBytes(bytes)
        }

        val result = patcher.apply(oldFile, broken, out, expected)

        assertTrue("esperava NativeFailure, veio $result", result is PatchResult.NativeFailure)
        assertEquals(HPatchCode.HDIFF_INFO_ERROR, (result as PatchResult.NativeFailure).code)
    }

    @Test
    fun hashEsperadoErrado_reprovaMesmoComPatchBom() {
        // Guards against the opposite bug: the module must not "fix" a wrong
        // manifest by accepting whatever came out.
        val result = patcher.apply(
            oldFile,
            patchFile,
            out,
            ExpectedApk("0".repeat(64), expectedNewSize),
        )

        assertTrue(result is PatchResult.IntegrityMismatch)
        assertEquals(expectedNewSha256, (result as PatchResult.IntegrityMismatch).actualSha256)
    }

    @Test
    fun patchAusente_naoEntraNoNativo() {
        val result = patcher.apply(oldFile, File(dir, "nao-existe.hdiff"), out, expected)

        assertTrue(result is PatchResult.InputMissing)
        assertEquals(PatchResult.InputRole.PATCH, (result as PatchResult.InputMissing).role)
    }
}
