pluginManagement {
    includeBuild("build-logic")
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "vps-manager-android"

// The pluginManagement includeBuild only covers plugin resolution. :lint-rules
// is an ordinary dependency, so it needs this top-level includeBuild too.
includeBuild("build-logic")

// Module generated by openapi-generator from the Go -> OpenAPI contract.
include(":data:mobile-api-client")

// Pure Kotlin/JVM module, no Android plugin.
include(":core")

include(":data")
include(":sdui")
include(":terminal-engine")
// Applies an HDiffPatch patch to the installed APK and verifies its SHA-256.
// No network or UI; download and install live in :data and :app.
include(":patch-engine")
include(":design-system")

// Instrumented benchmark comparing Canvas and SurfaceView under the same load.
include(":benchmark")

// Feature modules are named :feature-x but live in feature/x.
include(":feature-terminal")
project(":feature-terminal").projectDir = file("feature/terminal")
include(":feature-admin")
project(":feature-admin").projectDir = file("feature/admin")
include(":feature-auth")
project(":feature-auth").projectDir = file("feature/auth")
include(":feature-notifications")
project(":feature-notifications").projectDir = file("feature/notifications")
include(":feature-videocall")
project(":feature-videocall").projectDir = file("feature/videocall")
include(":feature-whatsapp")
project(":feature-whatsapp").projectDir = file("feature/whatsapp")
include(":feature-files")
project(":feature-files").projectDir = file("feature/files")
include(":feature-jira")
project(":feature-jira").projectDir = file("feature/jira")

include(":app")
