pluginManagement {
    includeBuild("build-logic")
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "vps-manager-android"

// includeBuild inside pluginManagement (above) only covers PLUGIN
// resolution. :lint-rules is consumed as an ordinary dependency (detektPlugins),
// which requires this second top-level includeBuild for dependency
// substitution by group:name to take effect.
includeBuild("build-logic")

// Module generated by openapi-generator from the Go -> OpenAPI contract.
include(":data:mobile-api-client")

// Pure Kotlin/JVM module — domain, SDUI contract, use-case interfaces.
// No Android plugin is applied to it (see android/core/build.gradle.kts).
include(":core")

// Android library modules.
include(":data")
include(":sdui")
include(":terminal-engine")
// Incremental update engine: applies an HDiffPatch patch over the installed
// APK and checks the SHA-256 of the result. No network and no UI — download and
// installation belong to :data and :app.
include(":patch-engine")
include(":design-system")

// Isolated instrumented module to measure Canvas vs SurfaceView under the same
// synthetic load.
include(":benchmark")

// Feature modules — the Gradle module name is flattened (:feature-x) but the
// directory on disk follows the feature/x tree.
include(":feature-terminal")
project(":feature-terminal").projectDir = file("feature/terminal")
include(":feature-admin")
project(":feature-admin").projectDir = file("feature/admin")
include(":feature-auth")
project(":feature-auth").projectDir = file("feature/auth")
include(":feature-notifications")
project(":feature-notifications").projectDir = file("feature/notifications")
include(":feature-videocall")
project(":feature-videocall").projectDir = file("feature/videocall")
include(":feature-whatsapp")
project(":feature-whatsapp").projectDir = file("feature/whatsapp")
include(":feature-files")
project(":feature-files").projectDir = file("feature/files")
include(":feature-jira")
project(":feature-jira").projectDir = file("feature/jira")

// :app — the only module with real (non-placeholder) content so far: theme,
// edge-to-edge, navigation and the Home vertical slice against the generated client.
include(":app")
