package sdui

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

type Contract struct {
	SDUIVersion      int                          `json:"sdui_version"`
	GeneratedFrom    string                       `json:"generated_from"`
	ComponentTypes   map[string]ComponentContract `json:"component_types"`
	Objects          map[string]ObjectContract    `json:"objects"`
	ActionDescriptor ObjectContract               `json:"action_descriptor"`
}

type ComponentContract struct {
	Fields map[string]FieldContract `json:"fields"`
}

type ObjectContract struct {
	Fields map[string]FieldContract `json:"fields"`
}

type FieldContract struct {
	JSONType string   `json:"json_type"`
	Required bool     `json:"required"`
	Const    string   `json:"const,omitempty"`
	Ref      string   `json:"ref,omitempty"`
	ItemRef  string   `json:"item_ref,omitempty"`
	Enum     []string `json:"enum,omitempty"`
}

var componentGoTypes = map[ComponentType]reflect.Type{
	ComponentTypeForm:               reflect.TypeOf(FormComponent{}),
	ComponentTypeTable:              reflect.TypeOf(TableComponent{}),
	ComponentTypeList:               reflect.TypeOf(ListComponent{}),
	ComponentTypeDetail:             reflect.TypeOf(DetailComponent{}),
	ComponentTypeAction:             reflect.TypeOf(ActionComponent{}),
	ComponentTypeChart:              reflect.TypeOf(ChartComponent{}),
	ComponentTypeConfirmDestructive: reflect.TypeOf(ConfirmDestructiveComponent{}),
}

func GenerateContract() Contract {
	c := Contract{
		SDUIVersion:    1,
		GeneratedFrom:  "internal/mobilebff/sdui (generated by cmd/sdui-contract, never written by hand)",
		ComponentTypes: make(map[string]ComponentContract, len(AllComponentTypes())),
		Objects:        make(map[string]ObjectContract),
	}

	for _, ct := range AllComponentTypes() {
		goType, ok := componentGoTypes[ct]
		if !ok {
			panic(fmt.Sprintf("sdui: %q is in AllComponentTypes() but not in componentGoTypes — the vocabulary and the contract generator fell out of sync", ct))
		}
		fields := make(map[string]FieldContract)
		walkComponentFields(goType, fields, &c, string(ct))
		c.ComponentTypes[string(ct)] = ComponentContract{Fields: fields}
	}

	c.ActionDescriptor = ObjectContract{Fields: fieldsOf(reflect.TypeOf(ActionDescriptor{}), &c)}

	return c
}

func walkComponentFields(t reflect.Type, fields map[string]FieldContract, c *Contract, typeConst string) {
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if f.Anonymous && f.Type.Kind() == reflect.Struct {
			walkComponentFields(f.Type, fields, c, typeConst)
			continue
		}
		if !f.IsExported() {
			continue
		}
		name, fc, ok := fieldContractFor(f, c)
		if !ok {
			continue
		}
		if name == "type" {
			fc.Const = typeConst
			fc.Required = true
		}
		fields[name] = fc
	}
}

func fieldsOf(t reflect.Type, c *Contract) map[string]FieldContract {
	fields := make(map[string]FieldContract)
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if !f.IsExported() {
			continue
		}
		name, fc, ok := fieldContractFor(f, c)
		if !ok {
			continue
		}
		fields[name] = fc
	}
	return fields
}

var (
	rawMessageType = reflect.TypeOf(json.RawMessage{})
	stringType     = reflect.TypeOf("")
)

func fieldContractFor(f reflect.StructField, c *Contract) (name string, fc FieldContract, ok bool) {
	tag := f.Tag.Get("json")
	if tag == "" || tag == "-" {
		return "", FieldContract{}, false
	}
	parts := strings.Split(tag, ",")
	name = parts[0]
	if name == "" {
		return "", FieldContract{}, false
	}
	omitempty := false
	for _, opt := range parts[1:] {
		if opt == "omitempty" {
			omitempty = true
		}
	}
	fc.Required = !omitempty

	ft := f.Type
	if ft.Kind() == reflect.Ptr {
		ft = ft.Elem()
	}

	switch {
	case ft == rawMessageType:
		fc.JSONType = "any"
	case ft.Kind() == reflect.String:
		fc.JSONType = "string"
	case ft.Kind() == reflect.Bool:
		fc.JSONType = "boolean"
	case isNumericKind(ft.Kind()):
		fc.JSONType = "number"
	case ft.Kind() == reflect.Slice, ft.Kind() == reflect.Array:
		fc.JSONType = "array"
		elem := ft.Elem()
		if elem.Kind() == reflect.Ptr {
			elem = elem.Elem()
		}
		if elem.Kind() == reflect.Struct {
			fc.ItemRef = registerObject(elem, c)
		}
	case ft.Kind() == reflect.Map:
		fc.JSONType = "object"
	case ft.Kind() == reflect.Struct:
		fc.JSONType = "object"
		fc.Ref = registerObject(ft, c)
	case ft.Kind() == reflect.Interface:
		fc.JSONType = "any"
	default:
		fc.JSONType = "any"
	}

	return name, fc, true
}

func isNumericKind(k reflect.Kind) bool {
	switch k {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return true
	default:
		return false
	}
}

func registerObject(t reflect.Type, c *Contract) string {
	name := t.Name()
	if _, exists := c.Objects[name]; exists {
		return name
	}
	c.Objects[name] = ObjectContract{}
	c.Objects[name] = ObjectContract{Fields: fieldsOf(t, c)}
	return name
}

func MarshalContract(c Contract) ([]byte, error) {
	b, err := json.MarshalIndent(c, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("sdui: marshal of the contract: %w", err)
	}
	return append(b, '\n'), nil
}
