package sdui

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

// Contract is the machine-readable manifest of the entire SDUI vocabulary,
// generated by reflection from this package's Go types — never maintained by
// hand. `cmd/sdui-contract` writes GenerateContract() into
// contracts/sdui/contract.json; contract_test.go proves the committed file is
// exactly that generated output (a drift test). This closes
// the documented pitfall: without a generated manifest, nothing detects when a field an
// already published app depends on stops being sent.
//
// Deliberately NOT JSON Schema: this manifest exists to answer only the two
// questions the contract diff needs to ask — "did a field a published client
// requires stop being mandatory/emitted?" and "can a published client render
// this fixture?" — and a purpose-built format answers both in ~60 lines of
// comparison, with no new dependency. Do not "upgrade" this to JSON Schema
// without a real reason (the only scenario ever entertained is a second
// renderer, iOS).
type Contract struct {
	SDUIVersion      int                          `json:"sdui_version"`
	GeneratedFrom    string                       `json:"generated_from"`
	ComponentTypes   map[string]ComponentContract `json:"component_types"`
	Objects          map[string]ObjectContract    `json:"objects"`
	ActionDescriptor ObjectContract               `json:"action_descriptor"`
}

// ComponentContract describes the fields of one of the 7 component types.
type ComponentContract struct {
	Fields map[string]FieldContract `json:"fields"`
}

// ObjectContract describes the fields of a supporting object referenced by
// Ref/ItemRef (DataSource, TableColumn, FormField, ActionDescriptor, ...).
type ObjectContract struct {
	Fields map[string]FieldContract `json:"fields"`
}

// FieldContract describes a single JSON field: its type, whether it is
// mandatory (derived from the absence of `omitempty` in the tag — never from
// a hand-written list), and, where applicable, a constant value, a reference
// to another object of the manifest, or an enum.
type FieldContract struct {
	JSONType string   `json:"json_type"` // "string" | "number" | "boolean" | "array" | "object" | "any"
	Required bool     `json:"required"`
	Const    string   `json:"const,omitempty"`
	Ref      string   `json:"ref,omitempty"`
	ItemRef  string   `json:"item_ref,omitempty"`
	Enum     []string `json:"enum,omitempty"`
}

// componentGoTypes maps each ComponentType to its concrete Go struct — used
// by GenerateContract to know what to reflect over. The same logical list as
// allComponentGoTypes in vocabulary_test.go, kept separate because one serves
// the contract generator (production) and the other the vocabulary guard
// (test); both are covered by TestContractComponentTypesMatchVocabulary.
var componentGoTypes = map[ComponentType]reflect.Type{
	ComponentTypeForm:               reflect.TypeOf(FormComponent{}),
	ComponentTypeTable:              reflect.TypeOf(TableComponent{}),
	ComponentTypeList:               reflect.TypeOf(ListComponent{}),
	ComponentTypeDetail:             reflect.TypeOf(DetailComponent{}),
	ComponentTypeAction:             reflect.TypeOf(ActionComponent{}),
	ComponentTypeChart:              reflect.TypeOf(ChartComponent{}),
	ComponentTypeConfirmDestructive: reflect.TypeOf(ConfirmDestructiveComponent{}),
}

// GenerateContract reflects over the 7 component structs (and over
// ActionDescriptor) and produces the complete Contract. It is the manifest's
// only source — cmd/sdui-contract calls this and nothing else to write
// contracts/sdui/contract.json.
func GenerateContract() Contract {
	c := Contract{
		SDUIVersion:    1,
		GeneratedFrom:  "internal/mobilebff/sdui (gerado por cmd/sdui-contract, nunca escrito à mão)",
		ComponentTypes: make(map[string]ComponentContract, len(AllComponentTypes())),
		Objects:        make(map[string]ObjectContract),
	}

	for _, ct := range AllComponentTypes() {
		goType, ok := componentGoTypes[ct]
		if !ok {
			panic(fmt.Sprintf("sdui: %q is in AllComponentTypes() but not in componentGoTypes — the vocabulary and the contract generator fell out of sync", ct))
		}
		fields := make(map[string]FieldContract)
		walkComponentFields(goType, fields, &c, string(ct))
		c.ComponentTypes[string(ct)] = ComponentContract{Fields: fields}
	}

	c.ActionDescriptor = ObjectContract{Fields: fieldsOf(reflect.TypeOf(ActionDescriptor{}), &c)}

	return c
}

// walkComponentFields walks t's exported fields (recursing into anonymous
// embeds, such as ComponentBase) and fills fields. The "type" field is
// handled separately: its constant value is typeConst itself (the component's
// discriminator), and it is always mandatory even if the struct tag one day
// gains an omitempty by mistake.
func walkComponentFields(t reflect.Type, fields map[string]FieldContract, c *Contract, typeConst string) {
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if f.Anonymous && f.Type.Kind() == reflect.Struct {
			walkComponentFields(f.Type, fields, c, typeConst)
			continue
		}
		if !f.IsExported() {
			continue
		}
		name, fc, ok := fieldContractFor(f, c)
		if !ok {
			continue
		}
		if name == "type" {
			fc.Const = typeConst
			fc.Required = true
		}
		fields[name] = fc
	}
}

// fieldsOf reflects the exported fields of a supporting struct (not a
// component — no special embedding logic), used both for ActionDescriptor
// and, via registerObject, for the referenced objects (DataSource,
// TableColumn, FormField, ...).
func fieldsOf(t reflect.Type, c *Contract) map[string]FieldContract {
	fields := make(map[string]FieldContract)
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if !f.IsExported() {
			continue
		}
		name, fc, ok := fieldContractFor(f, c)
		if !ok {
			continue
		}
		fields[name] = fc
	}
	return fields
}

var (
	rawMessageType = reflect.TypeOf(json.RawMessage{})
	stringType     = reflect.TypeOf("")
)

// fieldContractFor translates a reflect.StructField into a (JSON name,
// FieldContract) pair. It returns ok=false for fields with no json tag or
// marked "-". Referenced structs are registered in c.Objects (Ref); slices of
// structs register the element and point at ItemRef; json.RawMessage and any
// map to JSONType "any" — covering the awkward cases (embeds, pointers,
// json.RawMessage).
func fieldContractFor(f reflect.StructField, c *Contract) (name string, fc FieldContract, ok bool) {
	tag := f.Tag.Get("json")
	if tag == "" || tag == "-" {
		return "", FieldContract{}, false
	}
	parts := strings.Split(tag, ",")
	name = parts[0]
	if name == "" {
		return "", FieldContract{}, false
	}
	omitempty := false
	for _, opt := range parts[1:] {
		if opt == "omitempty" {
			omitempty = true
		}
	}
	fc.Required = !omitempty

	ft := f.Type
	if ft.Kind() == reflect.Ptr {
		ft = ft.Elem()
	}

	switch {
	case ft == rawMessageType:
		fc.JSONType = "any"
	case ft.Kind() == reflect.String:
		fc.JSONType = "string"
	case ft.Kind() == reflect.Bool:
		fc.JSONType = "boolean"
	case isNumericKind(ft.Kind()):
		fc.JSONType = "number"
	case ft.Kind() == reflect.Slice, ft.Kind() == reflect.Array:
		fc.JSONType = "array"
		elem := ft.Elem()
		if elem.Kind() == reflect.Ptr {
			elem = elem.Elem()
		}
		if elem.Kind() == reflect.Struct {
			fc.ItemRef = registerObject(elem, c)
		}
	case ft.Kind() == reflect.Map:
		fc.JSONType = "object"
	case ft.Kind() == reflect.Struct:
		fc.JSONType = "object"
		fc.Ref = registerObject(ft, c)
	case ft.Kind() == reflect.Interface:
		fc.JSONType = "any"
	default:
		fc.JSONType = "any"
	}

	return name, fc, true
}

func isNumericKind(k reflect.Kind) bool {
	switch k {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return true
	default:
		return false
	}
}

// registerObject makes sure t is in c.Objects (registering it the first time
// it is referenced) and returns the name Ref/ItemRef point at it by. A
// placeholder is written before recursing so as not to loop should a
// supporting type one day reference itself.
func registerObject(t reflect.Type, c *Contract) string {
	name := t.Name()
	if _, exists := c.Objects[name]; exists {
		return name
	}
	c.Objects[name] = ObjectContract{}
	c.Objects[name] = ObjectContract{Fields: fieldsOf(t, c)}
	return name
}

// MarshalContract is the manifest's only formatting point — used both by
// cmd/sdui-contract and by the drift test, so that the two can never disagree
// about indentation/line breaks.
func MarshalContract(c Contract) ([]byte, error) {
	b, err := json.MarshalIndent(c, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("sdui: marshal of the contract: %w", err)
	}
	return append(b, '\n'), nil
}
