package sdui

import (
	"bytes"
	"context"
	"flag"
	"strings"
	"testing"

	"server-control-panel/internal/config"
)

// updateGoldenScreens is Go's standard golden-test flag: running with
// `-update` regenerates the files instead of comparing them. `make
// sdui-golden` is the only sanctioned way to invoke it.
var updateGoldenScreens = flag.Bool("update", false, "regenera os goldens de tela SDUI em contracts/sdui/fixtures/screens/")

// screensGoldenDir is where the screen goldens live — inside the same
// Go/Kotlin shared fixture tree (see fixtures/README.md), in a subfolder of
// their own because these are generated by Build() from a synthetic Viewer,
// not hand-written like the rest of the corpus.
const screensGoldenDir = fixturesDir + "/screens"

// screensWithNoRoleDifference is the explicit, reviewed allowlist of screens
// whose admin golden and non-admin golden are byte-identical ON PURPOSE — a
// screen with no admin-only content at all is legitimate, but it needs an
// entry here with the reason written down, because the alternative (no entry)
// is indistinguishable from "nobody checked". Key: the screen id. Value: the reason.
//
// A new screen is added here ONLY if, after looking at its Builder, the
// genuine conclusion is "there is no per-role content difference" —
// otherwise the screen belongs in forbiddenForNonAdmin, not here.
var screensWithNoRoleDifference = map[string]string{
	"docker.volumes":  "list-only for any viewer: internal/docker exposes no single-item delete for volumes, and the web panel (handleVolumes) is read-only too — there is no admin-only action or data to omit.",
	"docker.networks": "list-only for any viewer: internal/docker exposes no single-item delete for networks, and the web panel (handleNetworks) is read-only too — there is no admin-only action or data to omit.",
	"system.history":  "list-only for any viewer: handleHistory has no admin gate in the web panel, and the Builder (buildSystemHistoryScreen) neither receives nor consults the Viewer — there is no admin-only action or data to omit.",
	"system.ports":    "list-only for any viewer: handleListening has no admin gate in the web panel, and the Builder (buildSystemPortsScreen) neither receives nor consults the Viewer — there is no admin-only action or data to omit, and no removal of a listening socket either.",
	"system.metrics":  "list-only for any viewer: history/metrics has no admin gate in the web panel. The screen's only per-viewer content is the Value of the window field (systemMetricsWindowFor(v.Username)), which is per-USER state, not per-ROLE — the two golden viewers (golden-admin/golden-user) never called system.metrics.window, so both read the same defaultSystemMetricsWindow and the golden comes out byte-identical; this is not an RBAC omission, it is the same default value read twice.",
	"jira.issues":     "the gate is by per-user CREDENTIAL (MiscDeps.JiraStatus(v.Username)), never by IsAdmin() — buildJiraIssuesScreen does not even consult v.IsAdmin(). The golden harness wires both synthetic viewers (golden-admin/golden-user) to the same fake Jira state, so both see the SAME connected screen; this is not an RBAC omission, it is a screen whose visibility axis is a different one.",
	"queue.jobs":      "list-only for any authenticated viewer: buildQueueJobsScreen receives the Viewer but does not even consult it — the screen structure (table + retry/cancel actions + confirm_destructive) is identical for everyone. The real per-role scoping happens in the rows ENDPOINT (queue.jobs.rows in RegisterMisc: owner=\"\" for admin, owner=v.Username for non-admin), outside the Envelope this golden compares, and in the ownership check inside the action handlers (misc_actions.go) — it is not an RBAC omission in the Builder, it is RBAC living in two layers that this golden does not reach.",
}

// forbiddenForNonAdmin is the living registry of "what a non-admin golden may
// never contain" per screen — a func, not a static slice, so that an entry
// can DERIVE its set from the same authorization source the screen's Builder
// used (e.g. the set of primary-only scheduler queue kinds is the difference
// between what is authorized for an admin and what is authorized for a
// non-admin), instead of freezing a hand-picked sample. A hand-picked sample
// silently leaves the rest of the set unprotected; a derived set stays
// correct as the underlying universe grows.
//
// Every screen registered in RegisteredScreens() whose admin golden differs
// from its non-admin golden, and that has no entry here, fails
// TestGoldenScreens_RoleOmissionIsReasoned — this is what stops a wave of new
// screens from spreading twenty unreviewed RBAC surfaces: adding a new screen
// means adding its entry here (or in
// screensWithNoRoleDifference); a screen that skips both fails CI.
var forbiddenForNonAdmin = map[string]func() []string{}

// lookupForbiddenForNonAdmin merges forbiddenForNonAdmin (screens defined
// inside this package) with the external registry in rbac_registry.go
// (RegisterForbiddenForNonAdmin) — the valve that lets a screen defined
// outside sdui (e.g. internal/mobilebff/screens, which imports sdui and
// therefore cannot be imported back by a file of this package without
// creating a cycle) take part in the same two checks as an internal screen.
func lookupForbiddenForNonAdmin(screenID string) (func() []string, bool) {
	if fn, ok := forbiddenForNonAdmin[screenID]; ok {
		return fn, true
	}
	return forbiddenForNonAdminExtEntry(screenID)
}

// testGoldenViewers builds the two synthetic Viewers through the SAME
// construction path production uses (config.Config + ViewerFrom) — never a
// literal Viewer{} — so that the goldens exercise the real admin resolution,
// not an assumption about what ViewerFrom would do.
func testGoldenViewers() map[string]Viewer {
	cfg := &config.Config{
		SchemaVersion: config.CurrentSchemaVersion,
		Primary:       "golden-admin",
		Users: []config.User{
			{Username: "golden-admin", PasswordHash: "h"},
			{Username: "golden-user", PasswordHash: "h"},
		},
	}
	return map[string]Viewer{
		"admin":    ViewerFrom(cfg, "golden-admin"),
		"nonadmin": ViewerFrom(cfg, "golden-user"),
	}
}

// TestGoldenScreens is Test 1 (and, via the flag, Test 2): it builds every
// registered screen for the two synthetic roles and compares against the
// committed goldens; with `-update`, it regenerates instead of
// comparing. With zero registered screens (Test 5), both loops do nothing
// and the test passes trivially — that is why this harness can be merged
// before a real SDUI screen exists.
func TestGoldenScreens(t *testing.T) {
	screens := RegisteredScreens()
	viewers := testGoldenViewers()

	if *updateGoldenScreens {
		if err := WriteGoldens(screensGoldenDir, screens, viewers); err != nil {
			t.Fatalf("WriteGoldens: %v", err)
		}
		t.Logf("goldens regenerated in %s for %d screen(s)", screensGoldenDir, len(screens))
		return
	}

	diffs, err := CompareGoldens(screensGoldenDir, screens, viewers)
	if err != nil {
		t.Fatalf("CompareGoldens: %v", err)
	}
	for _, d := range diffs {
		t.Errorf("screen %q, role %q: %s\nrun `make sdui-golden` and review the diff", d.Screen, d.Role, d.Detail)
	}
}

// TestGoldenScreens_EmptyRegistryPassesTrivially pins, without depending on
// the current state of RegisteredScreens(), that zero screens is a valid,
// silent case — not a harness error.
func TestGoldenScreens_EmptyRegistryPassesTrivially(t *testing.T) {
	diffs, err := CompareGoldens(t.TempDir(), []string{}, testGoldenViewers())
	if err != nil {
		t.Fatalf("CompareGoldens with zero screens should not fail: %v", err)
	}
	if len(diffs) != 0 {
		t.Fatalf("CompareGoldens with zero screens should return 0 diffs, got %d", len(diffs))
	}
}

// TestGoldenScreens_RoleOmissionIsReasoned is Test 3: every registered
// screen must either (a) have different admin and non-admin goldens
// (the difference IS the proof that somebody looked at RBAC), or (b) be in
// screensWithNoRoleDifference with a written reason. Neither of the two is
// the same as "nobody checked".
func TestGoldenScreens_RoleOmissionIsReasoned(t *testing.T) {
	ctx := context.Background()
	viewers := testGoldenViewers()

	for _, screen := range RegisteredScreens() {
		adminOut, err := buildGoldenBytes(ctx, screen, viewers["admin"])
		if err != nil {
			t.Fatalf("buildando %q (admin): %v", screen, err)
		}
		nonAdminOut, err := buildGoldenBytes(ctx, screen, viewers["nonadmin"])
		if err != nil {
			t.Fatalf("buildando %q (nonadmin): %v", screen, err)
		}

		identical := bytes.Equal(adminOut, nonAdminOut)
		reason, allowlisted := screensWithNoRoleDifference[screen]

		if identical && !allowlisted {
			t.Errorf("screen %q: the admin golden and the non-admin golden are byte-identical and the screen is not in screensWithNoRoleDifference — if this is intentional, add an entry with the reason; if not, either the screen leaks admin-only content to everyone, or the Builder is not filtering anything by mistake", screen)
		}
		if identical && allowlisted && reason == "" {
			t.Errorf("screen %q: entry in screensWithNoRoleDifference with no reason written", screen)
		}

		if !identical {
			if _, ok := lookupForbiddenForNonAdmin(screen); !ok {
				t.Errorf("screen %q: the admin golden and the non-admin golden DIFFER but there is no entry in forbiddenForNonAdmin (not even via RegisterForbiddenForNonAdmin) — register the set of what the non-admin golden must never contain", screen)
			}
		}
	}
}

// TestGoldenScreens_NonAdminNeverContainsForbiddenStrings is Test 4: for
// every screen with an entry in forbiddenForNonAdmin, the non-admin
// golden may contain none of the strings that entry returns — checked over
// the golden's real bytes, not over a structural
// assumption.
func TestGoldenScreens_NonAdminNeverContainsForbiddenStrings(t *testing.T) {
	ctx := context.Background()
	viewers := testGoldenViewers()

	for _, screen := range RegisteredScreens() {
		forbiddenFn, ok := lookupForbiddenForNonAdmin(screen)
		if !ok {
			continue // a missing registration is already reported by TestGoldenScreens_RoleOmissionIsReasoned where applicable
		}

		nonAdminOut, err := buildGoldenBytes(ctx, screen, viewers["nonadmin"])
		if err != nil {
			t.Fatalf("buildando %q (nonadmin): %v", screen, err)
		}

		for _, forbidden := range forbiddenFn() {
			if strings.Contains(string(nonAdminOut), forbidden) {
				t.Errorf("screen %q: the non-admin golden contains %q, which forbiddenForNonAdmin declares forbidden for this role", screen, forbidden)
			}
		}
	}
}
