#!/usr/bin/env bash
# Generates the fixtures for the REAL CYCLE test (ApkPatcherRealApkTest): two
# release APKs signed with the development key and the HDiffPatch patch
# between them, in build/patch-fixtures/ (an androidTest assets srcDir in
# build.gradle.kts).
#
# Not committed: the pair plus patch is about 66 MB of opaque binary, and this
# script rebuilds it in about 4 minutes. The committed SMALL pair
# (tools/make-smoke-fixtures.sh) covers .so loading, the JNI signature and
# hash checking on a clean checkout.
#
# Without running this script first, ApkPatcherRealApkTest FAILS rather than
# skipping, so a green suite always includes the real-cycle proof.
#
# Usage: ./tools/make-patch-fixtures.sh
# Env:   KEYSTORE=<jks>  HDIFFZ=<binary>  ABI=<x86_64|arm64-v8a>

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODULE_DIR="$(dirname "$SCRIPT_DIR")"
ANDROID_DIR="$(dirname "$MODULE_DIR")"
OUT_DIR="$MODULE_DIR/build/patch-fixtures/patch-fixtures"
STAGE_DIR="$MODULE_DIR/.build/apks"

# x86_64 by default because tests run on the emulator. Releases are
# arm64-v8a, but to the patcher an APK is just bytes, so the cycle is the same.
ABI="${ABI:-x86_64}"
KEYSTORE="${KEYSTORE:-/opt/panel/data/android-dev-signing/vpsmanager-DEV-NAO-E-RELEASE.jks}"

OLD_VERSION_NAME="${OLD_VERSION_NAME:-0.1.5}"
OLD_VERSION_CODE="${OLD_VERSION_CODE:-105}"
NEW_VERSION_NAME="${NEW_VERSION_NAME:-0.1.6}"
NEW_VERSION_CODE="${NEW_VERSION_CODE:-106}"

HDIFFZ="${HDIFFZ:-$MODULE_DIR/.build/hdiffz}"
if [ ! -x "$HDIFFZ" ]; then
  HDIFFZ="$(command -v hdiffz || true)"
fi
if [ -z "$HDIFFZ" ] || [ ! -x "$HDIFFZ" ]; then
  echo "make-patch-fixtures: hdiffz not found (see tools/make-smoke-fixtures.sh for how to build it)" >&2
  exit 1
fi
if [ ! -f "$KEYSTORE" ]; then
  echo "make-patch-fixtures: development keystore missing: $KEYSTORE" >&2
  echo "  (this is NOT the release key, which never touches this machine)" >&2
  exit 1
fi

mkdir -p "$STAGE_DIR" "$OUT_DIR"

build_apk() {
  local version_name="$1" version_code="$2" dest="$3"
  echo "make-patch-fixtures: build $version_name ($version_code) abi=$ABI" >&2
  ( cd "$ANDROID_DIR" && ./gradlew :app:assembleRelease \
      "-PversionName=$version_name" \
      "-PversionCode=$version_code" \
      "-Pvpsmanager.devKeystore=$KEYSTORE" \
      "-Pvpsmanager.abi=$ABI" >/dev/null )
  cp -f "$ANDROID_DIR/app/build/outputs/apk/release/app-release.apk" "$dest"
}

build_apk "$OLD_VERSION_NAME" "$OLD_VERSION_CODE" "$STAGE_DIR/old.apk"
build_apk "$NEW_VERSION_NAME" "$NEW_VERSION_CODE" "$STAGE_DIR/new.apk"

# Same options as the server's generator. -s-4m (stream mode) keeps the
# patching memory peak low on the phone; -c-zstd is what production uses.
echo "make-patch-fixtures: hdiffz -s-4m -c-zstd-21-24" >&2
"$HDIFFZ" -s-4m -c-zstd-21-24 -f "$STAGE_DIR/old.apk" "$STAGE_DIR/new.apk" "$STAGE_DIR/update.hdiff" >/dev/null

cp -f "$STAGE_DIR/old.apk"      "$OUT_DIR/base.apk"
cp -f "$STAGE_DIR/update.hdiff" "$OUT_DIR/update.hdiff"

# The NEW APK is deliberately not copied into the assets: the test only needs
# its SHA-256 and size, not another 33 MB inside the test APK.
NEW_SHA="$(sha256sum "$STAGE_DIR/new.apk" | cut -d' ' -f1)"
NEW_SIZE="$(stat -c%s "$STAGE_DIR/new.apk")"
OLD_SHA="$(sha256sum "$STAGE_DIR/old.apk" | cut -d' ' -f1)"

cat > "$OUT_DIR/expected.properties" <<EOF
# Generated by tools/make-patch-fixtures.sh, do not edit by hand.
# Describes the APK that applying update.hdiff to base.apk MUST produce.
abi=$ABI
oldVersionName=$OLD_VERSION_NAME
oldVersionCode=$OLD_VERSION_CODE
oldSha256=$OLD_SHA
newVersionName=$NEW_VERSION_NAME
newVersionCode=$NEW_VERSION_CODE
newSha256=$NEW_SHA
newSizeBytes=$NEW_SIZE
patchSizeBytes=$(stat -c%s "$STAGE_DIR/update.hdiff")
baseSizeBytes=$(stat -c%s "$STAGE_DIR/old.apk")
EOF

echo >&2
cat "$OUT_DIR/expected.properties" >&2
echo >&2
echo "make-patch-fixtures: done in $OUT_DIR" >&2
