#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODULE_DIR="$(dirname "$SCRIPT_DIR")"
ANDROID_DIR="$(dirname "$MODULE_DIR")"
OUT_DIR="$MODULE_DIR/build/patch-fixtures/patch-fixtures"
STAGE_DIR="$MODULE_DIR/.build/apks"

ABI="${ABI:-x86_64}"
KEYSTORE="${KEYSTORE:-/opt/panel/data/android-dev-signing/servercontrolpanel-DEV-NOT-RELEASE.jks}"

OLD_VERSION_NAME="${OLD_VERSION_NAME:-0.1.5}"
OLD_VERSION_CODE="${OLD_VERSION_CODE:-105}"
NEW_VERSION_NAME="${NEW_VERSION_NAME:-0.1.6}"
NEW_VERSION_CODE="${NEW_VERSION_CODE:-106}"

HDIFFZ="${HDIFFZ:-$MODULE_DIR/.build/hdiffz}"
if [ ! -x "$HDIFFZ" ]; then
  HDIFFZ="$(command -v hdiffz || true)"
fi
if [ -z "$HDIFFZ" ] || [ ! -x "$HDIFFZ" ]; then
  echo "make-patch-fixtures: hdiffz not found (see tools/make-smoke-fixtures.sh for how to build it)" >&2
  exit 1
fi
if [ ! -f "$KEYSTORE" ]; then
  echo "make-patch-fixtures: development keystore missing: $KEYSTORE" >&2
  echo "  (this is NOT the release key, which never touches this machine)" >&2
  exit 1
fi

mkdir -p "$STAGE_DIR" "$OUT_DIR"

build_apk() {
  local version_name="$1" version_code="$2" dest="$3"
  echo "make-patch-fixtures: build $version_name ($version_code) abi=$ABI" >&2
  ( cd "$ANDROID_DIR" && ./gradlew :app:assembleRelease \
      "-PversionName=$version_name" \
      "-PversionCode=$version_code" \
      "-Pservercontrolpanel.devKeystore=$KEYSTORE" \
      "-Pservercontrolpanel.abi=$ABI" >/dev/null )
  cp -f "$ANDROID_DIR/app/build/outputs/apk/release/app-release.apk" "$dest"
}

build_apk "$OLD_VERSION_NAME" "$OLD_VERSION_CODE" "$STAGE_DIR/old.apk"
build_apk "$NEW_VERSION_NAME" "$NEW_VERSION_CODE" "$STAGE_DIR/new.apk"

echo "make-patch-fixtures: hdiffz -s-4m -c-zstd-21-24" >&2
"$HDIFFZ" -s-4m -c-zstd-21-24 -f "$STAGE_DIR/old.apk" "$STAGE_DIR/new.apk" "$STAGE_DIR/update.hdiff" >/dev/null

cp -f "$STAGE_DIR/old.apk"      "$OUT_DIR/base.apk"
cp -f "$STAGE_DIR/update.hdiff" "$OUT_DIR/update.hdiff"

NEW_SHA="$(sha256sum "$STAGE_DIR/new.apk" | cut -d' ' -f1)"
NEW_SIZE="$(stat -c%s "$STAGE_DIR/new.apk")"
OLD_SHA="$(sha256sum "$STAGE_DIR/old.apk" | cut -d' ' -f1)"

cat > "$OUT_DIR/expected.properties" <<EOF
# Generated by tools/make-patch-fixtures.sh, do not edit by hand.
# Describes the APK that applying update.hdiff to base.apk MUST produce.
abi=$ABI
oldVersionName=$OLD_VERSION_NAME
oldVersionCode=$OLD_VERSION_CODE
oldSha256=$OLD_SHA
newVersionName=$NEW_VERSION_NAME
newVersionCode=$NEW_VERSION_CODE
newSha256=$NEW_SHA
newSizeBytes=$NEW_SIZE
patchSizeBytes=$(stat -c%s "$STAGE_DIR/update.hdiff")
baseSizeBytes=$(stat -c%s "$STAGE_DIR/old.apk")
EOF

echo >&2
cat "$OUT_DIR/expected.properties" >&2
echo >&2
echo "make-patch-fixtures: done in $OUT_DIR" >&2
