package webassets

// minified.go — decides WHEN the .min.js may stand in for the .js.
//
// 🔴 WHY THIS FILE EXISTS
//
// The server prefers `<x>.min.js` over `<x>.js` when the minified file exists.
// That was a choice made on PRESENCE: the file is there => serve the file. And
// presence says nothing about PROVENANCE.
//
// The `.min.js` is a GENERATED and UNTRACKED artifact (see .gitignore). It
// survives in the directory after the `.js` that produced it has already
// changed — and `make minify` is best-effort, so any build path that skips it
// leaves the stale artifact standing. That is what happened: a stale
// `00-shell.min.js` went on being served after `00-shell.js` gained the AdGuard
// state. index.html (not minified, always fresh) started referencing
// `adguardLoaded` and the bundle being served did not have the property:
//
//   ReferenceError: adguardLoaded is not defined
//
// Alpine evaluates template expressions at boot; a ReferenceError there does not
// degrade one section, it takes down the whole app — the "unexpected front-end
// error" screen.
//
// The fix is not "remember to run minify". It is making the stale artifact
// UNUSABLE: `make minify` stamps the sha256 of the originating `.js` at the end
// of the `.min.js`, and here we only accept the minified file whose stamp
// matches the hash of the source that is in the SAME embed. Missing or diverging
// stamp => serve the original.
//
// Fails open on purpose, in the same spirit as the pre-existing "esbuild missing
// => serve the original": the worst case becomes "the site loads a few KB more",
// never "the site does not load".

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"io/fs"
	"path"
	"strings"
	"sync"
)

// stampPrefix opens the last line of the .min.js generated by the Makefile's
// `minify` target. Format: "//# vpsm-src-sha256=<64 hex>".
const stampPrefix = "//# vpsm-src-sha256="

// appDir is the only directory with minification — the third-party vendors
// (xterm, alpine, monaco) already arrive minified from upstream and do not pass here.
const appDir = "vendor/vpsm/app"

// validMinified maps "<x>.js" -> "<x>.min.js" only for the pairs where the
// minified file's stamp matches the sha256 of the source. Computed once: the
// embed is immutable at runtime and hashing 1 MB per request would be absurd.
var validMinified = sync.OnceValue(func() map[string]string {
	valid := map[string]string{}
	sub := SubFS()
	entries, err := fs.ReadDir(sub, appDir)
	if err != nil {
		return valid
	}
	for _, e := range entries {
		name := e.Name()
		if !strings.HasSuffix(name, ".js") || strings.HasSuffix(name, ".min.js") {
			continue
		}
		source := path.Join(appDir, name)
		min := path.Join(appDir, strings.TrimSuffix(name, ".js")+".min.js")
		if verify(sub, source, min) {
			valid[source] = min
		}
	}
	return valid
})

// verify reads the pair and answers whether the minified file was generated from THIS source.
func verify(sub fs.FS, source, min string) bool {
	bMin, err := fs.ReadFile(sub, min)
	if err != nil {
		return false
	}
	stamp, ok := readStamp(bMin)
	if !ok {
		return false
	}
	bSource, err := fs.ReadFile(sub, source)
	if err != nil {
		return false
	}
	sum := sha256.Sum256(bSource)
	return stamp == hex.EncodeToString(sum[:])
}

// readStamp extracts the hash from the last non-empty line of the minified file.
// It scans from the end backwards: the stamp is always the last line, and the
// minified body may contain the same sequence inside a string without that
// meaning provenance.
func readStamp(b []byte) (string, bool) {
	lines := bytes.Split(b, []byte("\n"))
	for i := len(lines) - 1; i >= 0; i-- {
		line := bytes.TrimSpace(lines[i])
		if len(line) == 0 {
			continue
		}
		if !bytes.HasPrefix(line, []byte(stampPrefix)) {
			return "", false // last useful line is not a stamp => no provenance
		}
		hash := string(bytes.TrimPrefix(line, []byte(stampPrefix)))
		if len(hash) != hex.EncodedLen(sha256.Size) {
			return "", false
		}
		if _, err := hex.DecodeString(hash); err != nil {
			return "", false
		}
		return hash, true
	}
	return "", false
}

// MinifiedOf returns the path of the minified file to serve in place of
// `source` (both relative to the SubFS, e.g. "vendor/vpsm/app/00-shell.js").
//
// ok=false when there is no minified file, when it carries no stamp, or when the
// stamp does not match the current source — in those cases the caller serves the original.
func MinifiedOf(source string) (string, bool) {
	min, ok := validMinified()[source]
	return min, ok
}
