package webassets

// minificado.go — decides WHEN the .min.js may stand in for the .js.
//
// 🔴 WHY THIS FILE EXISTS
//
// The server prefers `<x>.min.js` over `<x>.js` when the minified file exists.
// That was a choice made on PRESENCE: the file is there => serve the file. And
// presence says nothing about PROVENANCE.
//
// The `.min.js` is a GENERATED and UNTRACKED artifact (see .gitignore). It
// survives in the directory after the `.js` that produced it has already
// changed — and `make minify` is best-effort, so any build path that skips it
// leaves the stale artifact standing. That is what happened: a stale
// `00-shell.min.js` went on being served after `00-shell.js` gained the AdGuard
// state. index.html (not minified, always fresh) started referencing
// `adguardLoaded` and the bundle being served did not have the property:
//
//   ReferenceError: adguardLoaded is not defined
//
// Alpine evaluates template expressions at boot; a ReferenceError there does not
// degrade one section, it takes down the whole app — the "unexpected front-end
// error" screen.
//
// The fix is not "remember to run minify". It is making the stale artifact
// UNUSABLE: `make minify` stamps the sha256 of the originating `.js` at the end
// of the `.min.js`, and here we only accept the minified file whose stamp
// matches the hash of the source that is in the SAME embed. Missing or diverging
// stamp => serve the original.
//
// Fails open on purpose, in the same spirit as the pre-existing "esbuild missing
// => serve the original": the worst case becomes "the site loads a few KB more",
// never "the site does not load".

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"io/fs"
	"path"
	"strings"
	"sync"
)

// carimboPrefixo opens the last line of the .min.js generated by the Makefile's
// `minify` target. Format: "//# vpsm-src-sha256=<64 hex>".
const carimboPrefixo = "//# vpsm-src-sha256="

// dirDoApp is the only directory with minification — the third-party vendors
// (xterm, alpine, monaco) already arrive minified from upstream and do not pass here.
const dirDoApp = "vendor/vpsm/app"

// minificadosValidos maps "<x>.js" -> "<x>.min.js" only for the pairs where the
// minified file's stamp matches the sha256 of the source. Computed once: the
// embed is immutable at runtime and hashing 1 MB per request would be absurd.
var minificadosValidos = sync.OnceValue(func() map[string]string {
	validos := map[string]string{}
	sub := SubFS()
	entradas, err := fs.ReadDir(sub, dirDoApp)
	if err != nil {
		return validos
	}
	for _, e := range entradas {
		nome := e.Name()
		if !strings.HasSuffix(nome, ".js") || strings.HasSuffix(nome, ".min.js") {
			continue
		}
		fonte := path.Join(dirDoApp, nome)
		min := path.Join(dirDoApp, strings.TrimSuffix(nome, ".js")+".min.js")
		if confere(sub, fonte, min) {
			validos[fonte] = min
		}
	}
	return validos
})

// confere reads the pair and answers whether the minified file was generated from THIS source.
func confere(sub fs.FS, fonte, min string) bool {
	bMin, err := fs.ReadFile(sub, min)
	if err != nil {
		return false
	}
	carimbo, ok := leCarimbo(bMin)
	if !ok {
		return false
	}
	bFonte, err := fs.ReadFile(sub, fonte)
	if err != nil {
		return false
	}
	soma := sha256.Sum256(bFonte)
	return carimbo == hex.EncodeToString(soma[:])
}

// leCarimbo extracts the hash from the last non-empty line of the minified file.
// It scans from the end backwards: the stamp is always the last line, and the
// minified body may contain the same sequence inside a string without that
// meaning provenance.
func leCarimbo(b []byte) (string, bool) {
	linhas := bytes.Split(b, []byte("\n"))
	for i := len(linhas) - 1; i >= 0; i-- {
		linha := bytes.TrimSpace(linhas[i])
		if len(linha) == 0 {
			continue
		}
		if !bytes.HasPrefix(linha, []byte(carimboPrefixo)) {
			return "", false // last useful line is not a stamp => no provenance
		}
		hash := string(bytes.TrimPrefix(linha, []byte(carimboPrefixo)))
		if len(hash) != hex.EncodedLen(sha256.Size) {
			return "", false
		}
		if _, err := hex.DecodeString(hash); err != nil {
			return "", false
		}
		return hash, true
	}
	return "", false
}

// MinificadoDe returns the path of the minified file to serve in place of
// `fonte` (both relative to the SubFS, e.g. "vendor/vpsm/app/00-shell.js").
//
// ok=false when there is no minified file, when it carries no stamp, or when the
// stamp does not match the current source — in those cases the caller serves the original.
func MinificadoDe(fonte string) (string, bool) {
	min, ok := minificadosValidos()[fonte]
	return min, ok
}
