package mobilebff

import (
	"context"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/danielgtaylor/huma/v2"
	"github.com/danielgtaylor/huma/v2/adapters/humago"

	"server-control-panel/internal/auth"
	"server-control-panel/internal/config"
	"server-control-panel/internal/httpx"
	ptysvc "server-control-panel/internal/pty"
	"server-control-panel/internal/sessionbackup"
)

func init() { Register("terminal-backup", registerTerminalBackup) }

type clientIPKey struct{}

func withAudit(ctx huma.Context, next func(huma.Context)) {
	req, w := humago.Unwrap(ctx)
	if auth.UserFrom(req) == "" {
		httpx.WriteErr(w, http.StatusUnauthorized, "unauthorized")
		return
	}
	next(huma.WithValue(ctx, clientIPKey{}, auth.ClientIP(req)))
}

func recordAudit(ctx context.Context, log *auth.AuditLog, user, action, target string) {
	if log == nil {
		return
	}
	ip, _ := ctx.Value(clientIPKey{}).(string)
	log.Append(auth.Event{User: user, Action: action, Target: target, IP: ip})
}

type BackupSessionSummary struct {
	Name    string `json:"name"`
	Summary string `json:"summary"`
	Lines   int    `json:"lines"`
}

type BackupSummary struct {
	ID       string                 `json:"id"`
	Created  int64                  `json:"created"`
	Source   string                 `json:"source,omitempty"`
	Bytes    int64                  `json:"bytes"`
	Sessions []BackupSessionSummary `json:"sessions"`
}

type backupsListOutput struct {
	Body []BackupSummary
}

type CreateBackupRequest struct {
	Name string `json:"name,omitempty" doc:"Session to save; empty = all of them in one bundle"`
}

type createBackupInput struct {
	IdemKey string `header:"Idempotency-Key" doc:"Key generated by the device; repeating the same key returns the first result without running again"`
	Body    CreateBackupRequest
}

type CreateBackupResponse struct {
	ID      string `json:"id"`
	Created int64  `json:"created"`
	Count   int    `json:"count"`
}

type createBackupOutput struct {
	Body CreateBackupResponse
}

type RestoreBackupRequest struct {
	ID   string `json:"id"`
	Name string `json:"name,omitempty" doc:"Session to restore; empty = every session in the backup"`
}

type restoreBackupInput struct {
	IdemKey string `header:"Idempotency-Key" doc:"Key generated by the device; repeating the same key returns the first result without running again"`
	Body    RestoreBackupRequest
}

type RestoreBackupResponse struct {
	Restored int `json:"restored"`
	Skipped  int `json:"skipped"`
}

type restoreBackupOutput struct {
	Body RestoreBackupResponse
}

type deleteBackupInput struct {
	ID      string `path:"id" doc:"Id do backup"`
	Name    string `query:"name" doc:"Removes only this session from the backup; empty = the whole backup"`
	IdemKey string `header:"Idempotency-Key" doc:"Key generated by the device; repeating the same key returns the first result without running again"`
}

type deleteBackupOutput struct {
	Body struct {
		Status string `json:"status"`
	}
}

type RenameSessionRequest struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type renameSessionInput struct {
	IdemKey string `header:"Idempotency-Key" doc:"Key generated by the device; repeating the same key returns the first result without running again"`
	Body    RenameSessionRequest
}

type statusOutput struct {
	Body struct {
		Status string `json:"status"`
	}
}

func dataDirOf(cfg *config.Config) string {
	if cfg == nil {
		return ""
	}
	return cfg.DataDir
}

func registerTerminalBackup(api huma.API, deps Deps) {
	cfg := deps.Cfg
	own := deps.SessionOwn
	audit := deps.Audit
	store := sessionbackup.New(dataDirOf(cfg))

	huma.Register(api, huma.Operation{
		OperationID: "listTerminalBackups",
		Method:      http.MethodGet,
		Path:        "/terminal/backups",
		Summary:     "The user's session backups, newest first",
		Tags:        []string{"mobile", "terminal"},
		Middlewares: huma.Middlewares{requireAuth},
		Errors:      []int{http.StatusUnauthorized},
	}, listBackupsHandler(store))

	huma.Register(api, huma.Operation{
		OperationID: "createTerminalBackup",
		Method:      http.MethodPost,
		Path:        "/terminal/backups",
		Summary:     "Saves the current state of one session (or all of them)",
		Tags:        []string{"mobile", "terminal"},
		Middlewares: huma.Middlewares{withAudit},
		Errors:      []int{http.StatusUnauthorized, http.StatusNotFound, http.StatusBadRequest},
	}, createBackupHandler(cfg, own, audit, store, deps.Idem))

	huma.Register(api, huma.Operation{
		OperationID: "restoreTerminalBackup",
		Method:      http.MethodPost,
		Path:        "/terminal/backups/restore",
		Summary:     "Recreates the sessions of a backup (skips the ones that already exist)",
		Tags:        []string{"mobile", "terminal"},
		Middlewares: huma.Middlewares{withAudit},
		Errors:      []int{http.StatusUnauthorized, http.StatusNotFound, http.StatusBadRequest},
	}, restoreBackupHandler(own, audit, store, deps.Idem))

	huma.Register(api, huma.Operation{
		OperationID: "deleteTerminalBackup",
		Method:      http.MethodDelete,
		Path:        "/terminal/backups/{id}",
		Summary:     "Deletes a backup, or just one session inside it",
		Tags:        []string{"mobile", "terminal"},
		Middlewares: huma.Middlewares{withAudit},
		Errors:      []int{http.StatusUnauthorized, http.StatusNotFound, http.StatusBadRequest},
	}, deleteBackupHandler(audit, store, deps.Idem))

	huma.Register(api, huma.Operation{
		OperationID: "renameTerminalSession",
		Method:      http.MethodPost,
		Path:        "/terminal/sessions/rename",
		Summary:     "Renames a session, carrying its ownership along",
		Tags:        []string{"mobile", "terminal"},
		Middlewares: huma.Middlewares{withAudit},
		Errors:      []int{http.StatusUnauthorized, http.StatusNotFound, http.StatusBadRequest},
	}, renameSessionHandler(cfg, own, audit, deps.Idem))

}

func listBackupsHandler(store *sessionbackup.Store) func(context.Context, *struct{}) (*backupsListOutput, error) {
	return func(ctx context.Context, _ *struct{}) (*backupsListOutput, error) {
		user := auth.UserFromContext(ctx)
		metadata := store.List(user)
		out := make([]BackupSummary, 0, len(metadata))
		for _, m := range metadata {
			sessions := make([]BackupSessionSummary, 0, len(m.Sessions))
			for _, s := range m.Sessions {
				sessions = append(sessions, BackupSessionSummary{Name: s.Name, Summary: s.Summary, Lines: s.Lines})
			}
			out = append(out, BackupSummary{
				ID: m.ID, Created: m.Created, Source: m.Source, Bytes: m.Bytes, Sessions: sessions,
			})
		}
		return &backupsListOutput{Body: out}, nil
	}
}

func createBackupHandler(
	cfg *config.Config,
	own *ptysvc.Ownership,
	audit *auth.AuditLog,
	store *sessionbackup.Store,
	idem *Idempotency,
) func(context.Context, *createBackupInput) (*createBackupOutput, error) {
	return func(ctx context.Context, in *createBackupInput) (*createBackupOutput, error) {
		return rememberResult(idem, keyFromContext(ctx, in.IdemKey), func() (*createBackupOutput, error) {
			user := auth.UserFromContext(ctx)
			primary := httpx.IsAdmin(cfg, user)

			var names []string
			if name := strings.TrimSpace(in.Body.Name); name != "" {
				if !ptysvc.OwnsSession(user, name, primary, own) {
					return nil, huma.Error404NotFound("session not found")
				}
				names = []string{name}
			} else {
				sessions, err := ptysvc.SessionListForUser(user, primary, own)
				if err != nil {
					return nil, huma.Error500InternalServerError("list sessions: " + err.Error())
				}
				for _, s := range sessions {
					if n, _ := s["name"].(string); n != "" {
						names = append(names, n)
					}
				}
			}
			if len(names) == 0 {
				return nil, huma.Error400BadRequest("no session to back up")
			}

			bk := ptysvc.Backup{
				ID:      strconv.FormatInt(time.Now().UnixNano(), 10),
				Created: time.Now().Unix(),
				Source:  sessionbackup.SourceManual,
			}
			for _, n := range names {
				snap, err := ptysvc.SnapshotSession(n, ptysvc.DefaultScrollbackLines)
				if err != nil {
					continue
				}
				bk.Sessions = append(bk.Sessions, snap)
			}
			if len(bk.Sessions) == 0 {
				return nil, huma.Error500InternalServerError("failed to capture the sessions")
			}
			if err := store.Write(user, bk); err != nil {
				return nil, huma.Error500InternalServerError(err.Error())
			}
			recordAudit(ctx, audit, user, "terminal.backup", bk.ID)

			out := &createBackupOutput{}
			out.Body = CreateBackupResponse{ID: bk.ID, Created: bk.Created, Count: len(bk.Sessions)}
			return out, nil
		})
	}
}

func restoreBackupHandler(
	own *ptysvc.Ownership,
	audit *auth.AuditLog,
	store *sessionbackup.Store,
	idem *Idempotency,
) func(context.Context, *restoreBackupInput) (*restoreBackupOutput, error) {
	return func(ctx context.Context, in *restoreBackupInput) (*restoreBackupOutput, error) {
		return rememberResult(idem, keyFromContext(ctx, in.IdemKey), func() (*restoreBackupOutput, error) {
			user := auth.UserFromContext(ctx)
			if !sessionbackup.ValidID(in.Body.ID) {
				return nil, huma.Error400BadRequest("invalid backup id")
			}
			bk, err := store.Read(user, in.Body.ID)
			if err != nil {
				return nil, huma.Error404NotFound("backup not found")
			}
			dir, err := store.Dir(user)
			if err != nil {
				return nil, huma.Error500InternalServerError(err.Error())
			}
			scratch := filepath.Join(dir, "scratch")
			_ = os.MkdirAll(scratch, 0o700)

			existing := len(own.SessionsOf(user))
			restored, skipped := 0, 0
			for _, s := range bk.Sessions {
				if in.Body.Name != "" && s.Name != ptysvc.SafeSessionName(in.Body.Name) {
					continue
				}
				if existing+restored >= ptysvc.MaxSessionsPerUser {
					skipped++
					continue
				}
				if err := ptysvc.RestoreSession(s, scratch); err != nil {
					skipped++
					continue
				}
				_ = own.Claim(ptysvc.SafeSessionName(s.Name), user)
				restored++
			}
			recordAudit(ctx, audit, user, "terminal.restore", in.Body.ID)

			out := &restoreBackupOutput{}
			out.Body = RestoreBackupResponse{Restored: restored, Skipped: skipped}
			return out, nil
		})
	}
}

func deleteBackupHandler(
	audit *auth.AuditLog,
	store *sessionbackup.Store,
	idem *Idempotency,
) func(context.Context, *deleteBackupInput) (*deleteBackupOutput, error) {
	return func(ctx context.Context, in *deleteBackupInput) (*deleteBackupOutput, error) {
		return rememberResult(idem, keyFromContext(ctx, in.IdemKey), func() (*deleteBackupOutput, error) {
			user := auth.UserFromContext(ctx)
			if !sessionbackup.ValidID(in.ID) {
				return nil, huma.Error400BadRequest("invalid backup id")
			}
			if err := store.Delete(user, in.ID, in.Name); err != nil {
				if os.IsNotExist(err) {
					return nil, huma.Error404NotFound("backup not found")
				}
				return nil, huma.Error500InternalServerError(err.Error())
			}
			target := in.ID
			if in.Name != "" {
				target += "#" + ptysvc.SafeSessionName(in.Name)
			}
			recordAudit(ctx, audit, user, "terminal.backup_delete", target)

			out := &deleteBackupOutput{}
			out.Body.Status = "ok"
			return out, nil
		})
	}
}

func renameSessionHandler(
	cfg *config.Config,
	own *ptysvc.Ownership,
	audit *auth.AuditLog,
	idem *Idempotency,
) func(context.Context, *renameSessionInput) (*statusOutput, error) {
	return func(ctx context.Context, in *renameSessionInput) (*statusOutput, error) {
		return rememberResult(idem, keyFromContext(ctx, in.IdemKey), func() (*statusOutput, error) {
			user := auth.UserFromContext(ctx)
			de := strings.TrimSpace(in.Body.From)
			stop := ptysvc.SafeSessionName(strings.TrimSpace(in.Body.To))
			if de == "" || stop == "" {
				return nil, huma.Error400BadRequest("from and to are required")
			}
			if !ptysvc.OwnsSession(user, de, httpx.IsAdmin(cfg, user), own) {
				return nil, huma.Error404NotFound("session not found")
			}
			if err := ptysvc.SessionRename(de, stop); err != nil {
				return nil, huma.Error500InternalServerError(err.Error())
			}
			_ = own.Rename(ptysvc.SafeSessionName(de), stop)
			recordAudit(ctx, audit, user, "terminal.rename", de+"→"+stop)

			out := &statusOutput{}
			out.Body.Status = "ok"
			return out, nil
		})
	}
}
