package mobilebff

import (
	"context"
	"net/http"
	"sort"
	"strings"

	"github.com/danielgtaylor/huma/v2"

	"server-control-panel/internal/auth"
	"server-control-panel/internal/config"
	"server-control-panel/internal/httpx"
	ptysvc "server-control-panel/internal/pty"
)

func init() { Register("terminal-sessions", registerTerminalSessions) }

type KillSessionRequest struct {
	Name string `json:"name" doc:"Name of the session to kill" required:"true"`
}

type killSessionInput struct {
	Body KillSessionRequest
}

type AssignSessionRequest struct {
	Name   string `json:"name" doc:"Session name" required:"true"`
	Target string `json:"target" doc:"Owner user, or '*' for everyone" required:"true"`
}

type assignSessionInput struct {
	IdemKey string `header:"Idempotency-Key" doc:"Key generated by the device; repeating the same key returns the first result without running again"`
	Body    AssignSessionRequest
}

type sessionPreviewInput struct {
	Name  string `query:"name" doc:"Session name" required:"true"`
	Lines int    `query:"lines" doc:"How many lines from the end (1..200)" default:"20"`
}

type SessionPreviewResponse struct {
	Name  string `json:"name"`
	Text  string `json:"text"`
	Lines int    `json:"lines"`
}

type AssignTargetsResponse struct {
	Targets []string `json:"targets" doc:"User names, plus \"*\" for everyone"`
}

type assignTargetsOutput struct {
	Body AssignTargetsResponse
}

type sessionPreviewOutput struct {
	Body SessionPreviewResponse
}

func registerTerminalSessions(api huma.API, deps Deps) {
	cfg := deps.Cfg
	own := deps.SessionOwn
	audit := deps.Audit

	huma.Register(api, huma.Operation{
		OperationID: "killTerminalSession",
		Method:      http.MethodPost,
		Path:        "/terminal/sessions/kill",
		Summary:     "Kills a session and the processes running in it",
		Tags:        []string{"mobile", "terminal"},
		Middlewares: huma.Middlewares{withAudit},
		Errors:      []int{http.StatusUnauthorized, http.StatusNotFound, http.StatusBadRequest},
	}, killSessionHandler(cfg, own, audit))

	huma.Register(api, huma.Operation{
		OperationID: "assignTerminalSession",
		Method:      http.MethodPost,
		Path:        "/terminal/sessions/assign",
		Summary:     "Sets who the session is shown to",
		Tags:        []string{"mobile", "terminal"},
		Middlewares: huma.Middlewares{withAudit},
		Errors:      []int{http.StatusUnauthorized, http.StatusNotFound, http.StatusBadRequest},
	}, assignSessionHandler(cfg, own, audit, deps.Idem))

	huma.Register(api, huma.Operation{
		OperationID: "previewTerminalSession",
		Method:      http.MethodGet,
		Path:        "/terminal/sessions/preview",
		Summary:     "The last lines of a session, without attaching to it",
		Tags:        []string{"mobile", "terminal"},
		Errors:      []int{http.StatusUnauthorized, http.StatusNotFound, http.StatusBadRequest},
	}, previewSessionHandler(cfg, own))

	huma.Register(api, huma.Operation{
		OperationID: "listAssignTargets",
		Method:      http.MethodGet,
		Path:        "/terminal/sessions/assign-targets",
		Summary:     "Who a session CAN be assigned to",
		Description: "Admin only. Lets the app OFFER the list instead of asking for a " +
			"typed user name: a typo here fails silently, because a nonexistent " +
			"target is accepted and the session disappears from everyone's list.",
		Tags:   []string{"mobile", "terminal"},
		Errors: []int{http.StatusUnauthorized, http.StatusNotFound},
	}, assignTargetsHandler(cfg))
}

func assignTargetsHandler(
	cfg *config.Config,
) func(context.Context, *struct{}) (*assignTargetsOutput, error) {
	return func(ctx context.Context, _ *struct{}) (*assignTargetsOutput, error) {
		user := auth.UserFromContext(ctx)
		if !httpx.IsAdmin(cfg, user) {
			return nil, huma.Error404NotFound("not found")
		}
		targets := make([]string, 0, len(cfg.Users)+1)
		for _, u := range cfg.Users {
			targets = append(targets, u.Username)
		}
		sort.Strings(targets)
		targets = append(targets, ptysvc.AudienceAll)

		out := &assignTargetsOutput{}
		out.Body.Targets = targets
		return out, nil
	}
}

func killSessionHandler(
	cfg *config.Config,
	own *ptysvc.Ownership,
	audit *auth.AuditLog,
) func(context.Context, *killSessionInput) (*statusOutput, error) {
	return func(ctx context.Context, in *killSessionInput) (*statusOutput, error) {
		user := auth.UserFromContext(ctx)
		name := strings.TrimSpace(in.Body.Name)
		if name == "" {
			return nil, huma.Error400BadRequest("name is required")
		}
		if !ptysvc.OwnsSession(user, name, httpx.IsAdmin(cfg, user), own) {
			return nil, huma.Error404NotFound("session not found")
		}
		if err := ptysvc.SessionKill(name); err != nil {
			return nil, huma.Error500InternalServerError(err.Error())
		}
		recordAudit(ctx, audit, user, "terminal.kill", name)

		out := &statusOutput{}
		out.Body.Status = "ok"
		return out, nil
	}
}

func assignSessionHandler(
	cfg *config.Config,
	own *ptysvc.Ownership,
	audit *auth.AuditLog,
	idem *Idempotency,
) func(context.Context, *assignSessionInput) (*statusOutput, error) {
	return func(ctx context.Context, in *assignSessionInput) (*statusOutput, error) {
		return rememberResult(idem, keyFromContext(ctx, in.IdemKey), func() (*statusOutput, error) {
			user := auth.UserFromContext(ctx)
			name := strings.TrimSpace(in.Body.Name)
			target := strings.TrimSpace(in.Body.Target)
			if name == "" || target == "" {
				return nil, huma.Error400BadRequest("name and target are required")
			}
			if !httpx.IsAdmin(cfg, user) {
				return nil, huma.Error404NotFound("session not found")
			}
			if !ptysvc.OwnsSession(user, name, true, own) {
				return nil, huma.Error404NotFound("session not found")
			}
			if err := own.Assign(ptysvc.SafeSessionName(name), target); err != nil {
				return nil, huma.Error500InternalServerError(err.Error())
			}
			recordAudit(ctx, audit, user, "terminal.assign", name+"→"+target)

			out := &statusOutput{}
			out.Body.Status = "ok"
			return out, nil
		})
	}
}

func previewSessionHandler(
	cfg *config.Config,
	own *ptysvc.Ownership,
) func(context.Context, *sessionPreviewInput) (*sessionPreviewOutput, error) {
	return func(ctx context.Context, in *sessionPreviewInput) (*sessionPreviewOutput, error) {
		user := auth.UserFromContext(ctx)
		name := strings.TrimSpace(in.Name)
		if name == "" {
			return nil, huma.Error400BadRequest("name is required")
		}
		if !ptysvc.OwnsSession(user, name, httpx.IsAdmin(cfg, user), own) {
			return nil, huma.Error404NotFound("session not found")
		}
		lines := in.Lines
		if lines <= 0 {
			lines = 20
		}
		if lines > 200 {
			lines = 200
		}
		text := ptysvc.SessionTail(name, lines)

		out := &sessionPreviewOutput{}
		out.Body = SessionPreviewResponse{
			Name:  name,
			Text:  text,
			Lines: lines,
		}
		return out, nil
	}
}
