package mobilebff

// handlers_terminal_sessions.go closes the distance between the web panel's
// sessions page and the app's: kill a session, decide who it shows up for and
// peek at what is running in it without attaching.
//
// There is no "detach" action: with the `dtach` backend, Detach is a no-op
// (dtach keeps no client list), so the button would do nothing.
//
// No new ownership rule is born here: it is the same `ptysvc.OwnsSession` as
// the panel, and the 404-instead-of-403 is deliberate — a 403 would confirm
// that the name exists in another account.

import (
	"context"
	"net/http"
	"sort"
	"strings"

	"github.com/danielgtaylor/huma/v2"

	"server-control-panel/internal/auth"
	"server-control-panel/internal/config"
	"server-control-panel/internal/httpx"
	ptysvc "server-control-panel/internal/pty"
)

func init() { Register("terminal-sessions", registerTerminalSessions) }

// KillSessionRequest — the name of the session to terminate.
type KillSessionRequest struct {
	Name string `json:"name" doc:"Name of the session to kill" required:"true"`
}

type killSessionInput struct {
	Body KillSessionRequest
}

// AssignSessionRequest — who the session starts showing up for.
//
// [Target] accepts a user or `*` for "everyone". It is the same vocabulary as the
// web panel's; translating it into an enum here would create two languages for the
// same field, and the translation would be wrong the day the panel accepted a new
// value.
type AssignSessionRequest struct {
	Name   string `json:"name" doc:"Session name" required:"true"`
	Target string `json:"target" doc:"Owner user, or '*' for everyone" required:"true"`
}

type assignSessionInput struct {
	// Assigning is already idempotent by nature (it forces the owner; repeating
	// gives the same result), but the key rides along because the action travels
	// in the SAME app queue as rename and delete — and a queue where only some
	// items carry a key is a queue with two rules.
	IdemKey string `header:"Idempotency-Key" doc:"Key generated by the device; repeating the same key returns the first result without running again"`
	Body    AssignSessionRequest
}

type sessionPreviewInput struct {
	Name string `query:"name" doc:"Session name" required:"true"`
	// The cap exists because the preview is a card, not a terminal: more than a
	// few dozen lines does not fit on screen and does not help decide whether
	// this is the session being looked for — which is the only question the
	// preview answers.
	Lines int `query:"lines" doc:"How many lines from the end (1..200)" default:"20"`
}

// SessionPreviewResponse — the last lines, already stripped of escapes.
//
// Plain text and not raw bytes, unlike `/terminal/raw-log`: that one feeds a
// terminal emulator and needs the escapes; this one feeds a preview card, where an
// escape is just garbage on screen.
type SessionPreviewResponse struct {
	Name  string `json:"name"`
	Text  string `json:"text"`
	Lines int    `json:"lines"`
}

// AssignTargetsResponse: the possible targets of a reassignment.
type AssignTargetsResponse struct {
	Targets []string `json:"targets" doc:"User names, plus \"*\" for everyone"`
}

type assignTargetsOutput struct {
	Body AssignTargetsResponse
}

type sessionPreviewOutput struct {
	Body SessionPreviewResponse
}

func registerTerminalSessions(api huma.API, deps Deps) {
	cfg := deps.Cfg
	own := deps.SessionOwn
	audit := deps.Audit

	huma.Register(api, huma.Operation{
		OperationID: "killTerminalSession",
		Method:      http.MethodPost,
		Path:        "/terminal/sessions/kill",
		Summary:     "Kills a session and the processes running in it",
		Tags:        []string{"mobile", "terminal"},
		Middlewares: huma.Middlewares{withAudit},
		Errors:      []int{http.StatusUnauthorized, http.StatusNotFound, http.StatusBadRequest},
	}, killSessionHandler(cfg, own, audit))

	huma.Register(api, huma.Operation{
		OperationID: "assignTerminalSession",
		Method:      http.MethodPost,
		Path:        "/terminal/sessions/assign",
		Summary:     "Sets who the session is shown to",
		Tags:        []string{"mobile", "terminal"},
		Middlewares: huma.Middlewares{withAudit},
		Errors:      []int{http.StatusUnauthorized, http.StatusNotFound, http.StatusBadRequest},
	}, assignSessionHandler(cfg, own, audit, deps.Idem))

	huma.Register(api, huma.Operation{
		OperationID: "previewTerminalSession",
		Method:      http.MethodGet,
		Path:        "/terminal/sessions/preview",
		Summary:     "The last lines of a session, without attaching to it",
		Tags:        []string{"mobile", "terminal"},
		Errors:      []int{http.StatusUnauthorized, http.StatusNotFound, http.StatusBadRequest},
	}, previewSessionHandler(cfg, own))

	huma.Register(api, huma.Operation{
		OperationID: "listAssignTargets",
		Method:      http.MethodGet,
		Path:        "/terminal/sessions/assign-targets",
		Summary:     "Who a session CAN be assigned to",
		Description: "Admin only. Lets the app OFFER the list instead of asking for a " +
			"typed user name: a typo here fails silently, because a nonexistent " +
			"target is accepted and the session disappears from everyone's list.",
		Tags:   []string{"mobile", "terminal"},
		Errors: []int{http.StatusUnauthorized, http.StatusNotFound},
	}, assignTargetsHandler(cfg))
}

func assignTargetsHandler(
	cfg *config.Config,
) func(context.Context, *struct{}) (*assignTargetsOutput, error) {
	return func(ctx context.Context, _ *struct{}) (*assignTargetsOutput, error) {
		user := auth.UserFromContext(ctx)
		// Same gate as assign, and for the same reason: whoever cannot reassign
		// cannot even enumerate the server's accounts.
		if !httpx.IsAdmin(cfg, user) {
			return nil, huma.Error404NotFound("not found")
		}
		targets := make([]string, 0, len(cfg.Users)+1)
		for _, u := range cfg.Users {
			targets = append(targets, u.Username)
		}
		sort.Strings(targets)
		// "*" last and on its own: it is the target that changes the outcome most (the
		// session starts showing up for EVERYONE) and it is not a user.
		targets = append(targets, ptysvc.AudienceAll)

		out := &assignTargetsOutput{}
		out.Body.Targets = targets
		return out, nil
	}
}

func killSessionHandler(
	cfg *config.Config,
	own *ptysvc.Ownership,
	audit *auth.AuditLog,
) func(context.Context, *killSessionInput) (*statusOutput, error) {
	return func(ctx context.Context, in *killSessionInput) (*statusOutput, error) {
		user := auth.UserFromContext(ctx)
		name := strings.TrimSpace(in.Body.Name)
		if name == "" {
			return nil, huma.Error400BadRequest("name is required")
		}
		if !ptysvc.OwnsSession(user, name, httpx.IsAdmin(cfg, user), own) {
			return nil, huma.Error404NotFound("session not found")
		}
		if err := ptysvc.SessionKill(name); err != nil {
			return nil, huma.Error500InternalServerError(err.Error())
		}
		recordAudit(ctx, audit, user, "terminal.kill", name)

		out := &statusOutput{}
		out.Body.Status = "ok"
		return out, nil
	}
}

func assignSessionHandler(
	cfg *config.Config,
	own *ptysvc.Ownership,
	audit *auth.AuditLog,
	idem *Idempotency,
) func(context.Context, *assignSessionInput) (*statusOutput, error) {
	return func(ctx context.Context, in *assignSessionInput) (*statusOutput, error) {
		return rememberResult(idem, keyFromContext(ctx, in.IdemKey), func() (*statusOutput, error) {
			user := auth.UserFromContext(ctx)
			name := strings.TrimSpace(in.Body.Name)
			target := strings.TrimSpace(in.Body.Target)
			if name == "" || target == "" {
				return nil, huma.Error400BadRequest("name and target are required")
			}
			// ONLY THE ADMIN REASSIGNS. Reassigning means giving ANOTHER account access
			// to a live shell — that is privilege escalation, not list tidying.
			// A non-admin does not even find out the session exists.
			if !httpx.IsAdmin(cfg, user) {
				return nil, huma.Error404NotFound("session not found")
			}
			if !ptysvc.OwnsSession(user, name, true, own) {
				return nil, huma.Error404NotFound("session not found")
			}
			if err := own.Assign(ptysvc.SafeSessionName(name), target); err != nil {
				return nil, huma.Error500InternalServerError(err.Error())
			}
			recordAudit(ctx, audit, user, "terminal.assign", name+"→"+target)

			out := &statusOutput{}
			out.Body.Status = "ok"
			return out, nil
		})
	}
}

func previewSessionHandler(
	cfg *config.Config,
	own *ptysvc.Ownership,
) func(context.Context, *sessionPreviewInput) (*sessionPreviewOutput, error) {
	return func(ctx context.Context, in *sessionPreviewInput) (*sessionPreviewOutput, error) {
		user := auth.UserFromContext(ctx)
		name := strings.TrimSpace(in.Name)
		if name == "" {
			return nil, huma.Error400BadRequest("name is required")
		}
		if !ptysvc.OwnsSession(user, name, httpx.IsAdmin(cfg, user), own) {
			return nil, huma.Error404NotFound("session not found")
		}
		lines := in.Lines
		// Clamped on both sides: 0 or negative would return empty and look like a
		// session with no output; above the cap it becomes a log transfer disguised
		// as a preview — and `/terminal/raw-log` exists for that.
		if lines <= 0 {
			lines = 20
		}
		if lines > 200 {
			lines = 200
		}
		text := ptysvc.SessionTail(name, lines)

		out := &sessionPreviewOutput{}
		out.Body = SessionPreviewResponse{
			Name:  name,
			Text:  text,
			Lines: lines,
		}
		return out, nil
	}
}
