package mobilebff

// idempotencia_http.go is the seam between the `Idempotency-Key` header the
// device sends and the result table in idempotencia.go.
//
// Why a function and not a middleware: huma does not let you swap the
// `http.ResponseWriter` inside the `huma.Context` — a middleware could only
// READ the response by rewriting the writer, and what is left is writing the
// bytes by hand and never calling `next` (the pattern in handlers_actions.go).
// That works, but it returns a raw body that skips huma's serialization, and
// the test then compares bytes instead of types. Here the result is stored and
// returned TYPED: the caller still returns a `*createBackupOutput`, and the
// retry returns the same value, not a lookalike copy.

import (
	"context"
	"encoding/json"
	"net/http"
	"strings"

	"server-control-panel/internal/auth"
)

// cabecalhoIdempotencia is the header's name, written down exactly once. The
// value is generated by the device (the id of the item in its outbound queue)
// and means nothing to the server beyond "this is the same action as before".
const cabecalhoIdempotencia = "Idempotency-Key"

// chaveDeIdempotencia builds the table key.
//
// The user ALWAYS goes into the key: two devices on different accounts can
// generate the same identifier, and a result leaking between accounts would be
// worse than having no idempotency at all (idempotencia.go:76-80).
//
// It returns empty when there is no header — and an empty key is a no-op in
// both methods of the table, so whoever does not send the header (the web
// panel, someone's curl) simply runs normally, with no special path.
func chaveDeIdempotencia(user, cabecalho string) string {
	c := strings.TrimSpace(cabecalho)
	if c == "" || user == "" {
		return ""
	}
	return user + ":" + c
}

// lembrarResultado runs `fn` at most ONCE per key, returning on a repeat the
// very same result as the first time.
//
// Three decisions worth explaining:
//
//  1. AN ERROR IS NOT REMEMBERED. An action that failed has to be able to
//     succeed on the retry — it was precisely a failure (of the network, of the
//     server) that put the item in the queue. Storing the error would turn the
//     queue into a machine for repeating the same defeat for 24 h.
//
//  2. AN UNREADABLE BODY RE-EXECUTES. If the response shape changed between the
//     first run and the retry (a deploy inside the 24 h window), the
//     `Unmarshal` fails. Re-executing is better than returning a half-filled
//     object: the action is idempotent enough for that — it is the reason it is
//     on this list in the first place.
//
//  3. THE WHOLE TYPE is serialized, not just the HTTP body. The format is
//     internal (nobody outside this function reads the file), and storing the
//     entire output struct keeps marshal and unmarshal symmetric, without a
//     second shape to keep up to date.
func lembrarResultado[T any](idem *Idempotencia, chave string, fn func() (*T, error)) (*T, error) {
	if idem == nil || chave == "" {
		return fn()
	}
	if corpo, _, ok := idem.Lembrada(chave); ok {
		var guardado T
		if err := json.Unmarshal([]byte(corpo), &guardado); err == nil {
			return &guardado, nil
		}
	}
	out, err := fn()
	if err != nil || out == nil {
		return out, err
	}
	if corpo, err := json.Marshal(out); err == nil {
		// Status 200 always: only success reaches this point. The field exists
		// in the table because the file on disk is read by humans when
		// something goes wrong, and a valueless "status" there would be worse
		// than one with a value.
		idem.Lembrar(chave, string(corpo), http.StatusOK)
	}
	return out, nil
}

// chaveDoContexto is the shortcut the handlers use: it takes the authenticated
// user from the context (the SAME source every handler already uses to
// authorize) and builds the key with the header that came in the input.
func chaveDoContexto(ctx context.Context, cabecalho string) string {
	return chaveDeIdempotencia(auth.UserFromContext(ctx), cabecalho)
}
