package mobilebff

// security.go — declaration of the mobile BFF's authentication scheme IN THE
// OpenAPI DOCUMENT (bearer JWT), on the Go side, where mobile-v1.yaml is born.
//
// Why this exists: the app's Kotlin client is 100% generated by
// org.openapi.generator out of android/data/mobile-api-client/openapi/
// mobile-v1.yaml, and the generator only emits authentication code for the
// operations that DECLARE security. While the spec declared nothing, the
// generated ApiClient was born with `accessToken`/`accessTokenProvider` fields
// and an `AUTHORIZATION` constant it NEVER referenced when building the
// request — dead hooks. Filling in ApiClient.accessToken authenticated not a
// single call, and every future regeneration of the client would reproduce the
// same hole. Declaring it here closes the contract at the source: the YAML is
// derived from this registry, never hand-edited.
//
// SCOPE: this is DESCRIPTIVE, not executive. huma v2.39.1 never reads
// Operation.Security on the request path — the field exists only for
// serializing the OpenAPI document (in openapi.go `Security` shows up in the
// MarshalJSON methods, and nowhere in huma.go, which is where the
// Register/handler pipeline lives). What actually demands the Bearer in
// production is still auth.Middleware, which wraps the "protected" mux in
// internal/api/api.go. Marking an operation here does NOT change server
// behaviour; it changes what the Kotlin generator emits.
//
// SPEC HONESTY: security is marked only on the routes registered through
// Register (Mount, under auth.Middleware). The RegisterPublic routes
// (MountPublic — /auth/login, /auth/refresh, /auth/pair, /auth/passkey/*) sit
// OUTSIDE the middleware on purpose (see the headers of auth_login.go and of
// registry_public.go) and are therefore born WITHOUT `security` in the
// document. A spec that declared security on them would lie — and it would make
// the generated client send a nonexistent Bearer on precisely the calls that
// happen before a session exists.

import "github.com/danielgtaylor/huma/v2"

// BearerSchemeName is the securityScheme's key in components.securitySchemes and
// the name referenced in each protected operation's `security`. Changing this
// string changes the name of the credential provider in the generated client —
// it is a contract change, and requires regenerating spec and client.
const BearerSchemeName = "bearerAuth"

// applyBearerSecurity registers the bearer scheme in the config and installs the
// hook that marks EVERY operation registered on that huma.API as protected.
//
// The hook (huma.Config.OnAddOperation, fired by OpenAPI.AddOperation on every
// huma.Register) is deliberately a single point: no handlers_*.go file has to
// remember to mark its own route, and a new endpoint cannot be born without
// declared security through forgetfulness — which is exactly how the original
// debt appeared.
func applyBearerSecurity(config *huma.Config) {
	if config.Components == nil {
		config.Components = &huma.Components{}
	}
	if config.Components.SecuritySchemes == nil {
		config.Components.SecuritySchemes = map[string]*huma.SecurityScheme{}
	}
	config.Components.SecuritySchemes[BearerSchemeName] = &huma.SecurityScheme{
		Type:         "http",
		Scheme:       "bearer",
		BearerFormat: "JWT",
		Description: "Access token emitido por POST /auth/login (ou renovado por " +
			"POST /auth/refresh), enviado como `Authorization: Bearer <token>`. " +
			"Quem valida é auth.Middleware, o mesmo de toda rota autenticada do painel.",
	}
	config.OnAddOperation = append(config.OnAddOperation, requireBearer)
}

// requireBearer marks an operation as requiring the bearer scheme. It respects a
// prior marking: if a registrar has already set Security (including an empty
// slice, which in OpenAPI means "explicitly no security"), its decision wins.
func requireBearer(_ *huma.OpenAPI, op *huma.Operation) {
	if op.Security != nil {
		return
	}
	op.Security = []map[string][]string{{BearerSchemeName: {}}}
}
