package deploy

import (
	"bufio"
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"
)

const hookScript = `#!/bin/sh
# server-control-panel post-receive: Heroku-style deploy. Generated by panelctl; do not edit.
# Reads <oldrev> <newrev> <refname> lines on stdin and hands them to panelctl.
exec panelctl app-deploy --name %q --hook
`

func Provision(name string) error {
	if !ValidName(name) {
		return fmt.Errorf("invalid app name: %q", name)
	}
	repo := RepoPath(name)
	if _, err := os.Stat(filepath.Join(repo, "HEAD")); err != nil {
		if err := os.MkdirAll(repo, 0o700); err != nil {
			return err
		}
		if out, err := exec.Command("git", "init", "--bare", repo).CombinedOutput(); err != nil {
			return fmt.Errorf("git init --bare: %v: %s", err, out)
		}
	}
	hook := filepath.Join(repo, "hooks", "post-receive")
	if err := os.MkdirAll(filepath.Dir(hook), 0o700); err != nil {
		return err
	}
	if err := os.WriteFile(hook, []byte(fmt.Sprintf(hookScript, name)), 0o755); err != nil {
		return fmt.Errorf("write hook: %w", err)
	}
	return os.MkdirAll(WorkDir(name, ""), 0o700)
}

func Deprovision(ctx context.Context, name string) error {
	_ = ComposeDown(ctx, ComposeProject(name, ""), WorkDir(name, ""), "docker-compose.yml", io.Discard)
	_ = os.RemoveAll(RepoPath(name))
	_ = os.RemoveAll(WorkDir(name, ""))
	return nil
}

type Spec struct {
	App      string
	Ref      string
	Commit   string
	Preview  string
	Trigger  string
	DeployID string
}

func NewID() string { return newDeployID() }

func newDeployID() string {
	var b [3]byte
	_, _ = rand.Read(b[:])
	return "d" + time.Now().UTC().Format("20060102-150405") + "-" + hex.EncodeToString(b[:])
}

func gitDir(ctx context.Context, repo string, args ...string) (string, error) {
	full := append([]string{"--git-dir=" + repo}, args...)
	out, err := exec.CommandContext(ctx, "git", full...).CombinedOutput()
	return strings.TrimSpace(string(out)), err
}

func Deploy(ctx context.Context, st *Store, spec Spec, logW io.Writer) (DeployRecord, error) {
	app, ok, err := st.Get(spec.App)
	if err != nil {
		return DeployRecord{}, err
	}
	if !ok {
		return DeployRecord{}, fmt.Errorf("app %q does not exist", spec.App)
	}
	branch := app.Branch
	if branch == "" {
		branch = "main"
	}
	composeFile := app.ComposeFile
	if composeFile == "" {
		composeFile = "docker-compose.yml"
	}
	ref := spec.Ref
	if ref == "" {
		ref = "refs/heads/" + branch
	}
	repo := RepoPath(app.Name)
	commit := spec.Commit
	if commit == "" {
		commit, err = gitDir(ctx, repo, "rev-parse", ref)
		if err != nil {
			return DeployRecord{}, fmt.Errorf("resolve %s: %w", ref, err)
		}
	}
	id := spec.DeployID
	if id == "" {
		id = newDeployID()
	}
	project := ComposeProject(app.Name, spec.Preview)
	workdir := WorkDir(app.Name, spec.Preview)

	logPath := st.LogPath(app.Name, id)
	_ = os.MkdirAll(filepath.Dir(logPath), 0o700)
	lf, _ := os.Create(logPath)
	var w io.Writer = logW
	if lf != nil {
		defer lf.Close()
		w = io.MultiWriter(logW, lf)
	}

	subject, _ := gitDir(ctx, repo, "log", "-1", "--format=%s", commit)
	rec := DeployRecord{
		ID: id, Ref: ref, Commit: commit, Preview: spec.Preview, Project: project,
		Status: "building", Started: time.Now().Unix(), Message: subject,
	}
	_ = st.AppendDeploy(app.Name, rec)

	fmt.Fprintf(w, "\n\033[1m▸ server-control-panel deploy\033[0m  app=%s  ref=%s  commit=%s\n", app.Name, ref, short(commit))
	if spec.Preview != "" {
		fmt.Fprintf(w, "  preview env: %s  (project %s)\n", spec.Preview, project)
	}
	if subject != "" {
		fmt.Fprintf(w, "  %s\n", subject)
	}

	fail := func(step string, e error) (DeployRecord, error) {
		fmt.Fprintf(w, "\n\033[31m✗ failed at %s: %v\033[0m\n", step, e)
		rec.Status = "failed"
		rec.Error = fmt.Sprintf("%s: %v", step, e)
		rec.Finished = time.Now().Unix()
		_ = st.AppendDeploy(app.Name, rec)
		return rec, fmt.Errorf("%s: %w", step, e)
	}

	fmt.Fprintf(w, "\n→ checkout %s → %s\n", short(commit), workdir)
	if err := os.MkdirAll(workdir, 0o700); err != nil {
		return fail("mkdir work-tree", err)
	}
	co := exec.CommandContext(ctx, "git", "-c", "advice.detachedHead=false",
		"--git-dir="+repo, "--work-tree="+workdir, "checkout", "-qf", commit)
	co.Stdout, co.Stderr = w, w
	if err := co.Run(); err != nil {
		return fail("git checkout", err)
	}

	env := map[string]string{}
	for k, v := range app.Env {
		env[k] = v
	}
	if spec.Preview != "" {
		for k, v := range app.PreviewEnv {
			env[k] = v
		}
	}
	port := app.Port
	if spec.Preview != "" {
		port = previewPort(app.Name, spec.Preview)
	}
	if port > 0 {
		if _, set := env["PORT"]; !set {
			env["PORT"] = strconv.Itoa(port)
		}
	}
	if err := writeDotEnv(filepath.Join(workdir, ".env"), env); err != nil {
		return fail("write .env", err)
	}
	fmt.Fprintf(w, "→ .env written (%d vars)\n", len(env))

	composePath := filepath.Join(workdir, composeFile)
	if _, err := os.Stat(composePath); err != nil {
		return fail("compose file", fmt.Errorf("%s not found in the repo", composeFile))
	}
	fmt.Fprintf(w, "\n→ docker compose up -d --build (project %s)\n", project)
	up := exec.CommandContext(ctx, "docker", "compose", "-p", project, "-f", composePath,
		"up", "-d", "--build", "--remove-orphans")
	up.Dir = workdir
	up.Stdout, up.Stderr = w, w
	if err := up.Run(); err != nil {
		return fail("docker compose up", err)
	}

	if dom := deployDomain(app, spec.Preview); dom != "" && port > 0 {
		if err := writeVhost(ctx, project, dom, port, w); err != nil {
			fmt.Fprintf(w, "\033[33m! nginx not configured: %v\033[0m\n", err)
		} else {
			fmt.Fprintf(w, "→ nginx: https://%s → 127.0.0.1:%d\n", dom, port)
		}
	}

	rec.Status = "running"
	rec.Finished = time.Now().Unix()
	_ = st.AppendDeploy(app.Name, rec)
	fmt.Fprintf(w, "\n\033[32m✓ deploy ready\033[0m  %s  (%ds)\n", project, rec.Finished-rec.Started)
	return rec, nil
}

func deployDomain(app App, preview string) string {
	if app.Domain == "" {
		return ""
	}
	if preview == "" {
		return app.Domain
	}
	return preview + "." + app.Domain
}

func short(sha string) string {
	if len(sha) > 12 {
		return sha[:12]
	}
	return sha
}

func writeDotEnv(path string, env map[string]string) error {
	keys := make([]string, 0, len(env))
	for k := range env {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("# generated by server-control-panel — do not edit (use the app's env UI)\n")
	for _, k := range keys {
		v := env[k]
		if strings.ContainsAny(v, "\n\r") {
			continue
		}
		fmt.Fprintf(&b, "%s=%s\n", k, v)
	}
	return os.WriteFile(path, []byte(b.String()), 0o600)
}

type HookRef struct {
	Ref    string
	Commit string
	Delete bool
}

func ParseHookStdin(r io.Reader) []HookRef {
	var out []HookRef
	sc := bufio.NewScanner(r)
	for sc.Scan() {
		f := strings.Fields(sc.Text())
		if len(f) != 3 {
			continue
		}
		newRev, ref := f[1], f[2]
		if strings.Trim(newRev, "0") == "" {
			out = append(out, HookRef{Ref: ref, Delete: true})
			continue
		}
		out = append(out, HookRef{Ref: ref, Commit: newRev})
	}
	return out
}
